### ISSUE TITLE
Lantern Raspberry Pi port

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#1617]
Need a working version ASAP. Will be a key prize for our upcoming Indiegogo campaign.

**Comment by uaalto** [comment]
Is this something we are still interested in? Maybe for the Go version?

**Comment by myleshorton** [comment]
Yes definitely! We actually have to do it because it was a prize for an Indiegogo campaign we did. We put it on hold with so much else going on but also because we wanted to make sure to include auto-updates from the Go version.

Actually, there's a pending task for this that would be interesting for you to take a peek at -- adding multicast discovery to make it possible to see the Lantern Pi running on the local network and to connect to it. We had that functionality in the java version but haven't ported it yet. Check out:

https://github.com/getlantern/lantern/issues/2462

**Comment by uaalto** [comment]
Great! I'll handle this. I've also identified a couple more issues/features that I can work on. Thank you!

**Comment by myleshorton** [comment]
Awesome @uaalto!

**Comment by uaalto** [comment]
Maybe we should close the issue with this pull request too: https://github.com/getlantern/lantern/pull/2646
Lantern runs on the Pi with these commits. The remaining step would be to integrate discovery on Lantern, which would be https://github.com/getlantern/lantern/issues/2462.
