### ISSUE TITLE
Router configuration message shows even if it's worked before with no network changes

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#1749]
This will happen if, for example, the server attempts to connect to the peer but it times out. With check-ins every two minutes, that's bound to happen eventually, especially with pretty aggressive timeouts on the server. So if you run for long enough, you're almost guaranteed to get the network configuration message.

**Comment by 1335654481ren** [comment]
Have you run lantern on you router ? and then anyone can get to net service by lantern agent on your router ? I build the lantern and have run it on my router ,I can get the service on the local site of my router,but not get the lantern service on my other devices,such as iphone，pc, How can I set the some rules on my router ,in order to lantern work well on my router.

**Comment by oxtoacart** [comment]
@1335654481ren Have you tried setting the addr and uiaddr like this?

```
./lantern -addr ":8787" -uiaddr ":16823" -headless
```
