### ISSUE TITLE
[feature] install updates automatically

### ISSUE THREAD

**Issue by skivvies** [getlantern/lantern#21]
evergreen style (e.g. à la Google Chrome).

Auto-updates using jardiff or something similar to auto-patch deployed jar files.

Sub-tasks:
- [ ] #898

**Comment by myleshorton** [comment]
One interesting option is to use Google's open source Omaha installer directly:

https://code.google.com/p/omaha/

It solves things that aren't obvious at first, such as bypassing UAC. 

This is somewhat similar on OSX:

https://code.google.com/p/update-engine/

**Comment by oxtoacart** [comment]
@myleshorton Excellent idea!  The one thing to watch out for is whether or not we can get it to work via our proxy, since censored users will quite possibly need to proxy the download of the update.

**Comment by myleshorton** [comment]
@oxtoacart Yeah we have the proxy issue with really any solution we use, and I don't think there's anything unique about Omaha in that regard.

**Comment by oxtoacart** [comment]
@myleshorton It's just a question of how do we get Omaha to use the proxy.  If we were doing custom Go code, for example, we could just have it use enproxy directly, the way that we already do for downloading cloud.yaml.  I don't know if Omaha has its own proxy settings that you can configure, or if you need to set a system proxy.

**Comment by myleshorton** [comment]
Right. It's deployed in all sorts of crazy corporate environments where that type of thing is a big deal, so I don't expect it to be an issue.

**Comment by myleshorton** [comment]
https://github.com/inconshreveable/go-update looks promising. Assigning to you @xiam

**Comment by xiam** [comment]
@myleshorton Cool!

I have some questions:

* Are we considering the current lantern release or our future Go release?
* Which platform should I focus on first? It could be OSX then Windows and finally Linux.

I think that if we focus on replacing binaries instead of patching a running process we could start testing this solution in a few days, that would be the most straightforward thing to do and that's what `go-update` already does so if it sounds right for you I could start with that.

**Comment by myleshorton** [comment]
> Are we considering the current lantern release or our future Go release?

This will be for a future Go release. We'll talk more about this on the call today, but we're going to prioritize a minimal version of the Go release to have ready by Valencia.

> Which platform should I focus on first? It could be OSX then Windows and finally Linux.

No preference really.

> I think that if we focus on replacing binaries instead of patching a running process we could start testing this solution in a few days, that would be the most straightforward thing to do and that's what go-update already does so if it sounds right for you I could start with that.

That sounds perfect!

**Comment by oxtoacart** [comment]
@xiam I agree that starting with a full update is a good start, but go-update also supports binary patching.

In fact, the [equinox](https://equinox.io/) service (built by Alan Shreve as well) handles all the difficult parts of [binary diffs](https://equinox.io/docs) for us.  It's [free](https://equinox.io/pricing) for open source projects, so I think we should just go ahead and use it.  The only tricky bit is that we'd need to patch the go-update API to support using our proxy to talk to the equinox servers (which shouldn't be hard).

**Comment by myleshorton** [comment]
Sounds good. On the binary diffs front, we'll just want to keep an eye out for whether or not they're really effective with compressed binaries, as the compression will likely completely throw off the diffs. Maybe we can update based on the uncompressed versions on disk, though, not sure.

**Comment by oxtoacart** [comment]
> Sounds good. On the binary diffs front, we'll just want to keep an eye out for whether or not they're really effective with compressed binaries

We should avoid compressing the binary itself (i.e. don't use upx).  Assuming that we're still using an installer to distribute the initial binary, the installer can and should be compressed and that won't have any impact on the binary diff since that's done on the binary itself, not the installer.

That reminds me - @xiam one of the design goals of our initial installer (which I'm taking a look at) is to have everything we need in the lantern/flashlight binary itself (e.g. web resources, helper programs, etc.), so for this task you only need to worry about updating the binary.

BTW, the rule about not using upx extends to any helper programs that we embed in lantern, as that ruins the binary diff for them.

**Comment by xiam** [comment]
I'm going to create an "autoupdate" repository to propose a solution for this, along with tests and documents. As far as I understand we don't actually have the final binary yet but we're going to prepare to work with only one binary, this binary itself must not be a compressed executable, but it can safely be gzipped (as a common file). 

Also, we should consider updating via proxy when the direct update fails and the binary diff is important because we also want to optimise our user's bandwidth usage.

I think that adding support for updating more than one file (for example, a PNG icon + flashlight binary + README) would not be that difficult and won't hurt at all, even if we finally manage to do everything in one single binary.

What do you think?

**Comment by myleshorton** [comment]
Agreed on all fronts @xiam! I think that's exactly what we want, with probably the multiple files as a last step that may or may not be necessary in the end.

**Comment by myleshorton** [comment]
See https://github.com/getlantern/autoupdate/issues/1

**Comment by xiam** [comment]
We have some progress on this issue. I built a [Go package](https://github.com/getlantern/autoupdate) around go-update and equinox.io that provides a binary with the ability to update itself, we can use it for the new Lantern binary.

Here's a [code example](https://github.com/getlantern/autoupdate/blob/master/_test_app/main.go) and [documentation](https://github.com/getlantern/autoupdate/tree/master/_test_app) on how to actually test it's working.

So the basic functionality is done :-).

What would be next? I can continue writing documentation and checking the security of the package but it would be awesome if I could jump into [go-lantern](https://github.com/getlantern/go-lantern) and try to bring up a real working demo. What do you think?

**Comment by oxtoacart** [comment]
@xiam I'm working on the first-time installers.  I already have Mac working, Windows is mostly there (needs some automation and documentation) and Linux is starting today.  I think once those are ready, that'll be a good time for us to pair on pulling in your changes, and I can review your autoupdate work at the same time.

In the meantime, do you want to grab another P1 item from the [queue](https://github.com/getlantern/lantern/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.0+Beta+1%22)?  As long as it's not assigned to anyone already, it's available.

**Comment by myleshorton** [comment]
Could this be useful on the compression front?

https://github.com/cloudflare/golz4

**Comment by myleshorton** [comment]
Hey @xiam you want me to just take a stab at updating the Windows and Linux installers to have user permissions?

**Comment by xiam** [comment]
Thanks! It would be really great if you could help me checking
options on Windows, that way I could skip it and get my hands directly on
the Linux installer.

**Comment by myleshorton** [comment]
OK cool -- I'll knock out the Windows installer changes over the weekend @xiam!

**Comment by xiam** [comment]
My proposed solution was just merged into our current dev branch! https://github.com/getlantern/flashlight-build/pull/55

Do we have any other concerns regarding auto-updates that would prevent us from closing this issue?

**Comment by xiam** [comment]
The corresponding LEP https://github.com/getlantern/lantern-roadmap/blob/master/lep/DRAFT/010_Updating_Lantern_Without_User_Intervention.md
