### ISSUE TITLE
[flashlight] Problems with register_domains.py on servers (missing pip)

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2119]
I saw this on a few servers when pushing the latest flashlight server configuration:

```
----------
          ID: salt-nodeps
    Function: pip.installed
        Name: salt==2014.1.10
      Result: False
     Comment: State pip.installed found in sls salt_minion is unavailable
     Changes:   
```

**Comment by oxtoacart** [comment]
@aranhoide Thanks very much for tracking this down!

**Comment by scouttle** [comment]
Just noticed that this ticket is closed – @aranhoide should it be moved to devel?

**Comment by aranhoide** [comment]
@scouttle I don't understand the question.  This ticket is about backend servers getting into a broken state.  Although some "code" (backend configuration in the lantern_aws project) changes were made as a result, the bulk of the fix involved manually massaging the servers back into shape.  Thus, the fix is deployed live.

You could call this a hotfix, although right now I admit we're not (yet) following the usual branching strategy for the lantern_aws project.
