### ISSUE TITLE
Can't get local friend to connect as Lantern friend

### ISSUE THREAD

**Issue by rngadam** [getlantern/lantern#2125]
MacOS X, Lantern version 1.5.14-9280775 (9280775), Shanghai

I'm sitting next to my friend who also has Lantern installed. 

Although we're both logged in and sent invite to each other through Lantern, all we got is those emails to invite us to install the software and our status shows as "Not yet connected". 

We're also both on Google Talk and that's working so we're not sure what is breaking down.

**Comment by myleshorton** [comment]
Thanks for the report @rngadam! 

The "Not yet connected" language is a little confusing. It just means that we haven't created an actual network connection between you and that friend and not that you're not yet considered friends. In the case you're talking about, Lantern actually won't connect the two of you because you're both in a censored region, so if Lantern tries to tunnel through either one of you, it won't really do any good. We have an existing ticket at #1371 to change that to make it less confusing.

**Comment by scouttle** [comment]
Indeed, thanks for the report, @rngadam! 

As @myleshorton, we hope to make this more clear over in #1371, so I'm going to close this issue for now. However, please chime in again if that doesn't seem right!
