### ISSUE TITLE
[www]unable to change language on smaller screens

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2173]
Found in css code that it is on purpose, but it does prevent user to access the function. Can we improve that? Like, just show nation code or flag on small screens.

**Comment by atavism** [comment]
@fffw Yeah, there's actually several instances where elements end up breaking on mobile, at least on certain devices. For tinier screens, the responsive nav stuff is supposed to convert the language drop-down into a small hamburger menu with the full list of languages to choose from. I like your idea of using flags/nation codes instead of the language names to reduce the row width and conserve screen space! If you take a look at https://github.com/getlantern/lantern/issues/1862 you'll be able to see some of the other problems: excessive space in the margins and some paragraph text failing to align properly -- is that something you'd maybe want to take a look at?

**Comment by fffw** [comment]
Seems the hamburger menu is for main nav, language selection dropdown is set [{display: none}](https://github.com/getlantern/www.getlantern.org/blob/master/app/styles/_top.scss#L109) on small screen.

Yes I'll take it but with lower priority.
