### ISSUE TITLE
Some DO servers still running old version of flashlight and consequently not registering with DO

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2222]
It's possible peerscanner is taking them out of rotation and they're never getting back in. If you look at the 30 day timeline in the following, it looks like that may have been the case in this instance (unclear how widespread this is). If this happens for a lot of servers, it'll obviously put more strain on the remaining ones and will make it more likely they'll get taken out too.

https://cloud.digitalocean.com/droplets/3674454

**Comment by myleshorton** [comment]
Also just in a quick scan on just one page, the following are the same:

https://cloud.digitalocean.com/droplets/3674591
https://cloud.digitalocean.com/droplets/3674684
https://cloud.digitalocean.com/droplets/3674782
https://cloud.digitalocean.com/droplets/3675668
https://cloud.digitalocean.com/droplets/3699601

**Comment by oxtoacart** [comment]
@myleshorton

> It's possible peerscanner is taking them out of rotation and they're never getting back in.

That's not what's happening.  I took a look at the list of servers and found ...

1. The following droplets aren't registered in CloudFlare at all (meaning that peerscanner is not the one that took them out, since peerscanner doesn't remove fallbacks from CloudFlare, just from rotation)

https://cloud.digitalocean.com/droplets/3674454
https://cloud.digitalocean.com/droplets/3674591
https://cloud.digitalocean.com/droplets/3675668
https://cloud.digitalocean.com/droplets/3699601

2. The following droplets are in the fallbacks rotation at the moment.  It's possible that they were temporarily overloaded and had been taken out of rotation.

https://cloud.digitalocean.com/droplets/3674684
https://cloud.digitalocean.com/droplets/3674782

I ssh'ed to the droplets that aren't registered in CloudFlare at all and found that they're running old versions of flashlight that don't register with peerscanner.  I'm pretty sure that this is the same problem I wrote about to the bns-ops list on Jan 21. Message quoted below:

> I just noticed that some recently launched fallbacks, like the 005 series, don't seem to be responding to highstate.

> ```
➜  lantern_aws git:(peerscanner) ✗ bin/ssh_cloudmaster.py 'salt -b 50 "fl-singapore-005-*" state.highstate'
Using controller: lantern-controller-afisk
Using cloudmaster: fisk-cloudmaster
➜  lantern_aws git:(peerscanner) ✗ 
```

> Note how nothing shows as added to the batch.  Also, when I spot-checked one of the 005 servers, it didn't show the most recent configuration.

> Any idea what's going on?

Updating title and bumping down to P2.

BTW, since this email, @aranhoide identified some issues with the salt script for peerscanner, which we fixed, but it occurs to me that the peerscanner script started as a copy of the flashlight script, so it likely has the same issues and could stand to be fixed.  Maybe that will resolve this.

**Comment by oxtoacart** [comment]
I just tried running highstate for one of these, and got the following:

```bash
➜  lantern_aws git:(master) ✗ bin/ssh_cloudmaster.py 'salt "ps-singapore-005-21" state.highstate'
Using controller: lantern-controller-afisk
Using cloudmaster: fisk-cloudmaster
No minions matched the target. No command was sent, no jid was assigned.
```

So, it looks like the cloudmaster doesn't even know about this nor likely the other similar servers.

**Comment by aranhoide** [comment]
I think you wrote `ps-` when you really meant `fl-`.

**Comment by aranhoide** [comment]
flashlight might be stuck in an old version if the relevant minions are not responding to the master.  Since this is causing such pain, I'll redeploy everything to a new cloudmaster this weekend, even if the cloudfront stuff is not done yet.

**Comment by oxtoacart** [comment]
Thanks @aranhoide!  FWIW, I really don't think it's such horrible pain.  As far as I can tell, this isn't impacting users, it's just wasting some money on unutilized DO droplets.  IMHO that can wait until after the weekend.

BTW, if try to run highstate against the correct name (fl-singapore-005-21) it still doesn't work.  However, after ssh'ing to the machine, I'm able to manually run highstate on there.  After that, running highstate via the cloudmaster works too.  Not sure if that helps, but it's what I observed.

**Comment by myleshorton** [comment]
Yeah I totally agree we should consolidate the cloudmasters. For some
reason I thought we had already done that but I guess not. Let's ditch
fisk-cloudmaster once and for all!

Thanks for the sleuthing Ox.

On Fri, Feb 6, 2015 at 8:15 PM, oxtoacart <notifications@github.com> wrote:

> Thanks @aranhoide <https://github.com/aranhoide>! FWIW, I really don't
> think it's such horrible pain. As far as I can tell, this isn't impacting
> users, it's just wasting some money on unutilized DO droplets. IMHO that
> can wait until after the weekend.
>
> BTW, if try to run highstate against the correct name
> (fl-singapore-005-21) it still doesn't work. However, after ssh'ing to the
> machine, I'm able to manually run highstate on there. After that, running
> highstate via the cloudmaster works too. Not sure if that helps, but it's
> what I observed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2222#issuecomment-73349011>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@aranhoide @myleshorton Do you think it would make sense to hold off on the consolidation until we've figured out what we're doing with #1763?  If we consolidate now, we'll likely have to stop some old servers and start some new ones.  Probably not a big deal either way.

**Comment by myleshorton** [comment]
I don't think it matters a whole lot, although I do think we need to get
the ball rolling on #1763 particularly for Iran.

On Saturday, February 7, 2015, oxtoacart <notifications@github.com> wrote:

> @aranhoide <https://github.com/aranhoide> @myleshorton
> <https://github.com/myleshorton> Do you think it would make sense to hold
> off on the consolidation until we've figured out what we're doing with
> #1763 <https://github.com/getlantern/lantern/issues/1763>? If we
> consolidate now, we'll likely have to stop some old servers and start some
> new ones. Probably not a big deal either way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2222#issuecomment-73362385>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by aranhoide** [comment]
All old servers have been killed.
