### ISSUE TITLE
Message for "Unable to listen at" error is confusing

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2253]
We're using a panic for a situation that could happen naturally at runtime and this may confuse the user, there is no need for the stack trace when the problem is that we have another application listening on the port flashlight attempted to use.

```
panic: Unable to start UI: Unable to listen at localhost:16823: <nil>

goroutine 7 [running]:
main.runClientProxy(0xc2080a2000)
        /home/reventlov/go/src/github.com/getlantern/flashlight-build/src/github.com/getlantern/flashlight/flashlight.go:162 +0x25a
main.doMain()
```

**Comment by oxtoacart** [comment]
Agreed.  In fact, what we need is a way to show a message box alerting the user to this (and similar) problems, since in production users won't have the console window.

**Comment by atavism** [comment]
We could use a lockfile to detect whether or not an instance of Lantern is already running and then just show an alert in the UI indicating this.

**Comment by oxtoacart** [comment]
+1 on detecting another instance of lantern.  Instead of using a lock file, we could just try to talk to it as if it's a lantern and if that works, consider it a lantern.  At that point, we could just open the UI again.

We'd still need to deal with the case that some other program is using that port, in which case we'd need to show an alert.  An alert in the UI won't work because there is no UI yet, so we'd have to show an OS-native dialog.

**Comment by myleshorton** [comment]
Agreed @oxtoacart. I actually think attempting to bind to a known port is
the cleanest way to do this, especially in go where I believe support
for lock files on windows is still a bit of a mess.

On Saturday, February 21, 2015, oxtoacart <notifications@github.com> wrote:

> +1 on detecting another instance of lantern. Instead of using a lock file,
> we could just try to talk to it as if it's a lantern and if that works,
> consider it a lantern. At that point, we could just open the UI again.
>
> We'd still need to deal with the case that some other program is using
> that port, in which case we'd need to show an alert. An alert in the UI
> won't work because there is no UI yet, so we'd have to show an OS-native
> dialog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2253#issuecomment-75378651>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by xiam** [comment]
Yeah, simple lock files sometimes cause problems, what if the program crashes or the machine's power is shutdown? The lock file would still be there.

I've seen other programs saving its PID to some file. Program like these read this file at startup and then look for the PID to determine if another instance is runing.

This is better than a lockfile because if the PID is not found then it means lantern is not running. If we want to be absolutely sure that the PID belongs to another Lantern instance perhaps we could send it a signal too.

**Comment by myleshorton** [comment]
Interesting on the saving a PID to a file @xiam, and I totally agree that straight lock files get problematic with crashes. I actually really like the combination of binding to a port and then if you can't bind attempting to tell the existing application to either open itself or close depending on what you want. The bind is nice because it's just as quick as checking a file, and only if there's a conflict do you have to worry about sending some message and getting a response. As @oxtoacart said, we also have to handle the bind conflict with other app regardless, and it's actually a good reason to change our port when we have this whole protocol implemented and know there's something that'll effectively listen on the other end (if it's Lantern =).
