### ISSUE TITLE
Deploy tools to measure Lantern performance in-country

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2286]
We need to run consistent Lantern performance monitoring in country. 

One tool to check out:

http://www.web-polygraph.org/

**Comment by oxtoacart** [comment]
Thanks for logging!

**Comment by myleshorton** [comment]
We could also start using RIPE atlas and/or Ooniprobe - just need to get credits.

**Comment by fffw** [comment]
Can we just add more dimensions and metrics to statreporter? Time required to establish enproxy between each pair, total time elapsed till first response, overall throughput of Lantern, top 10 sites with read/write bytes, etc...

Once we figured out the performance goal we want to measure, we can design metrics accordingly, and let statreporter continuously gather those data points, and report the calculated result periodically.

**Comment by myleshorton** [comment]
Yeah we certainly could do that @fffw! The main goal of this ticket is to track Lantern performance over time as we make changes intended to improve performance.

**Comment by myleshorton** [comment]
I think another [LEP](https://github.com/getlantern/lantern-roadmap/tree/master/lep) would be useful here. Would you be up for taking that one @fffw?

**Comment by oxtoacart** [comment]
@fffw Can we find some time to work on this together before I leave?  It would be good for someone other than me to know how statshub works.

**Comment by fffw** [comment]
@oxtoacart Are you available in the next 2 hours? I'll drop you an email to arrange time.

**Comment by fffw** [comment]
Ha I don’t have write privilege to lantern-roadmap. @myleshorton


BR,Merlin

**Comment by atavism** [comment]
@fffw You should have write access to lantern-roadmap now.

**Comment by fffw** [comment]
Thanks @atavism. LTE draft [here](https://github.com/getlantern/lantern-roadmap/blob/master/lep/DRAFT/011_Performance_Monitor_Goals_and_Metrics.md)

**Comment by myleshorton** [comment]
Awesome @fffw thanks! I forgot to mention this, but can you actually do this from a branch and then open a pull request to allow comments on that pull request? It'll just make commenting a bit easier!

**Comment by oxtoacart** [comment]
FWIW I love using hackpad because the commenting on there is even better.

Cheers,
Ox

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Comment by fffw** [comment]
Wasted so much time on the probe thing, I just realised that the most direct method might be to run Lantern in headless mode on selected VPS, and deploy a simple script to access Facebook/Twitter, download/upload file, etc., periodically.

To fully simulate the behaviour of an actual user, we have to launch a browser rather than just get the html file. Selenium WebDriver + PhantomJS might be a good choice. We may also choose Python for scripting as it's preinstalled on any Linux distro.

Further more, through pulling newest Lantern binary from build server, it can also act as our acceptance testing script, so if any of our feature breaks accessing to major sites, degrades the performance, or if the censor has changed their blocking rule, we can get noticed in the first place.

So its time to build a prototype rather than writing a LTE. How do you think @myleshorton ?

**Comment by fffw** [comment]
We can also stick on Go by using https://bitbucket.org/tebeka/selenium and our statreporter mechanism, to minimize our technology matrix.

**Comment by myleshorton** [comment]
I like that idea @fffw

**Comment by fffw** [comment]
Crafted a quick solution to monitor access time from in-country VPS to several sites, see https://github.com/getlantern/sonar/pull/1 and https://github.com/getlantern/lantern-dashboard/pull/1

**Comment by myleshorton** [comment]
Awesome! Can you guys review this -- maybe @xiam or @atavism?

**Comment by xiam** [comment]
Of course, looking at it.

**Comment by myleshorton** [comment]
Closing this since it's up at:

http://lantern-dashboard.s3-website-us-east-1.amazonaws.com/sonar.html

Interesting that Iran's load times are shooting up for some sites @fffw
