### ISSUE TITLE
Lantern Website - After selecting  a different language in the About page, if I navigate to the blog page - it still shows up in English. 

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#2301]
![blog page](https://cloud.githubusercontent.com/assets/11394369/6621510/fd2e221a-c8fc-11e4-9203-f950478d48b8.png)

In this file, I selected "Francais"

**Comment by aranhoide** [comment]
Something else may be wrong, then.  "O programu" and "Otázky" don't seem like French at all.

**Comment by sheena3** [comment]
oh I am sorry - it is Cestina. But I would like to know what are the contents that will change when selecting a different language. Because when selecting Cestina, I see many contents in About page is still displayed in English.

Also when selecting Cestina, it says "An app to end censorship" instead of "An app to end Internet censorship". 

![about page - cestina language](https://cloud.githubusercontent.com/assets/11394369/6622766/b521f958-c904-11e4-88a4-d509112623e7.png)
