### ISSUE TITLE
Always use direct proxies if they're available

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2321]
We shouldn't just weight the round robin.

**Comment by oxtoacart** [comment]
@myleshorton Can you please elaborate?    balancer already takes servers out of rotation if they're having trouble (e.g. blocked) and actually has more sophisticated checking than the old proxy tracker (it tries to get an actual web page).

**Comment by myleshorton** [comment]
Oh cool -- I'll remove that second sentence! That'll make it just using direct proxies if they're available.

**Comment by oxtoacart** [comment]
Is it good enough to just weight them heavily?  As currently configured, only 0.0054% of traffic will go through domain fronting, unless a bunch of the chained fallbacks are blocked.

**Comment by myleshorton** [comment]
I think in theory that accomplishes about what we want, but I just don't think the approach is quite right. We basically don't want to every use domain fronting unless we absolutely have to for a few reasons:

1. It's slower
1. It costs more
1. It's a shared resource amongst all tools using this technique, so we want to treat it as such to reduce the risk of blocking.

We should probably only ever use domain fronting if direct proxies are blocked, including for requests to required services.

**Comment by oxtoacart** [comment]
I understand.  One thing to keep in mind is that as long as we don't authenticate access to our platform somehow, anyone can mess with the configuration and use domain-fronting to their heart's content.

**Comment by aranhoide** [comment]
Yes, and I'd add that such abuse probably is probably accounting for the vast majority of domain fronted traffic as we speak.  I think this ticket is worth implementing nonetheless.

**Comment by oxtoacart** [comment]
@aranhoide I'm not saying that we shouldn't do this ticket, I'm just saying that this ticket by itself won't keep the domain-fronting cat in the proverbial bag.  However, if we implement some sort of entitlement mechanism, we might actually have a real hope of controlling and limiting domain-fronting traffic.

**Comment by aranhoide** [comment]
@oxtoacart sorry for the confusion. I just tried to make the point explicit.  I didn't think, nor meant to imply, that you meant otherwise.

OTOH, barring the ISP circumvention we're seeing in the Philippines, there's not much of an incentive to enable domain fronting while chained proxes are working, is there?

**Comment by oxtoacart** [comment]
> sorry for the confusion. I just tried to make the point explicit. I didn't think, nor meant to imply, that you meant otherwise.

We find ourselves in violent agreement :)

> OTOH, barring the ISP circumvention we're seeing in the Philippines, there's not much of an incentive to enable domain fronting while chained proxes are working, is there?

No, there's really not any point to forcing domain-fronting if the direct proxies are working, unless you don't like your traffic going through New York and prefer Amsterdam or Singapore for some reason.  I do think long term an entitlements mechanism will be beneficial because right now we're basically running infrastructure that's free for anyone to use as they see fit.  If I wanted to go launch a proxy product today that just piggybacks on Lantern's infrastructure, I could do so with no cost to me.  I could even charge for it.  Hmm ...

**Comment by myleshorton** [comment]
One idea that arose in outside discussion was the idea of simply using Nginx for these proxies. They'll be less fingerprintable and should perform better, but we'd need to fiddle with the configuration and/or add some modules to do all the things we need to do in terms of authentication and whatnot.

**Comment by oxtoacart** [comment]
One note about performance - the main thing we're interested in is latency.  In terms of overall CPU/Memory utilization it doesn't really matter because we're actually bandwidth constrained on our servers, not CPU or Memory constrained.

**Comment by aranhoide** [comment]
Is that true already, or only once we actually get charged for bandwidth?
We are seeing some flashlight alarms after all, so load average does get
bad sometimes?

**Comment by oxtoacart** [comment]
Hehe, true, as long as we're not actually being charged for the bandwidth we're using, we're not bandwidth-constrained :)  I've just never factored that into my calculations because I don't expect it to continue forever.  Also, as we start exploring other data centers, we will run into situations where we are charged for bandwidth.
