### ISSUE TITLE
Support running Lantern on system startup

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2344]

**Comment by aranhoide** [comment]
@atavism : I thought there was a simple option in fpm that would do this for us.  Unfortunately, that option is for making Lantern a service, which last I heard we don't really want.  What we used to do for the Java-based Lantern (and I checked this works) was to place a file in `~/.config/autostart/lantern-autostart.desktop` with the following content (this is edited from the 1.x lantern so it will work on 2.0):

```
[Desktop Entry]
Type=Application
Exec=lantern
Icon=lantern
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=Lantern
Name=Lantern
Comment[en_US]=
Comment=
```

This can live in the resources bundled with the executable or (perhaps easier) you can put it in the .deb installer and copy it to, e.g., `/usr/share/lantern/` on install, then copy it from there to `~/.config/autostart/` when the user enables autostart, and delete the latter when the user disables it.    Since this is under the user's home folder, you don't need superuser permissions.

To add a file to the .deb installer put it in <flashlight-build>/installer-resources/linux` and modify the Makefile to create (e.g.) `$$WORKDIR/usr/share/lantern` and copy the `lantern-autostart.desktop` to there.  

https://github.com/getlantern/flashlight-build/blob/valencia/Makefile#L48

Old Lantern had this enabled by default on install.   I don't know whether you want this; FWIW I think it's nicer and simpler to have it disabled by default and have the user opt in.   But if you want, you can enable it by default with a post-install script, which can be added with fpm's `--after-install` option.

**Comment by atavism** [comment]
Thanks, @aranhoide. We talked on the call Monday that we probably want to implement this as an upstart service to easily handle multiple distros. I've been testing my changes on Ubuntu and Fedora; it works fine with one important caveat: you have to run Lantern with sudo. You can't install/remove the service otherwise. I think that makes sense though, @myleshorton? We just present an error service settings can't be modified if the user is running Lantern without root access.

**Comment by myleshorton** [comment]
God, now I can't remember where the hell we landed on this on the call.

> We just present an error service settings can't be modified if the user is running Lantern without root access.

I don't understand that line. What do we present if the user's not running under sudo?

I'm certainly not against just doing it this way if it's basically done.

**Comment by atavism** [comment]
> I don't understand that line. What do we present if the user's not running under sudo?

I suggested an error message originally, but we could just not present the option at all in settings if we don't have sudo access. If we're only supporting Ubuntu though, @aranhoide's recommendation works fine.

**Comment by myleshorton** [comment]
What did you do for this on the Pi again?

**Comment by atavism** [comment]
I added a bash script to /etc/rc.local that runs Lantern on boot.

**Comment by myleshorton** [comment]
Gotcha. The Pi supports upstart too right? To me that might just tip the scales in favor of using your approach.

**Comment by aranhoide** [comment]
TBH I don't think asking our users to run Lantern as root is a minor issue or even acceptable if we can help it.  It considerably increases the stakes for every other security issue we get.  We went through some work to avoid doing that in our fallbacks (at least in the java version; I haven't checked what the new upstart scripts used by the Go version do) and I don't think we should be any less careful with users' machines.  I'd rather not offer autostart at all than encourage users to run the whole program as root.

**Comment by aranhoide** [comment]
And not all linux distros have upstart either.  I think cross distro/window manager/etc support is a fool's errand and we should stick to supporting Ubuntu well and welcome patches for other setups.

**Comment by aranhoide** [comment]
Also, if you're requiring sudo to modify this setting I'm guessing you're applying it system wide and not per user.  Not a huge deal, but still a disadvantage I think.

**Comment by atavism** [comment]
Actually, the library I was using isn't limited to upstart: it works with initd and runit too. That said, I agree we should be cautious and avoid asking users to run Lantern as root at all because of the security risks. Maybe we just do the autostart solution and explicitly limit our support to Ubuntu for now; we can revisit using a service when we release a headless build?

**Comment by aranhoide** [comment]
I don't know when we changed the messaging in getlantern.org to claim we have a "Linux" download, but I think that's a mistake.  Our download links used to be captioned "Ubuntu 12.04+ (32|64)bit", and I think that remains more accurate to this day.

I think the autostart trick is the best option, even if it only works on Ubuntu currently.  When we make a more focused push for wider Linux support I think we should research what other distros and Window managers are doing to automatically run a program on user login.  We are not going to ship a .deb for everyone, so some custom work per distro will be necessary anyway.

Now, if you really want to run this as a service, that doesn't require the Lantern program to run as root.  It only means you need root permissions to start it, stop it, and change autostart settings.  Our fallbacks (both Java and --I just checked-- Go versions) run as services with unprivileged user 'lantern'.

**Comment by myleshorton** [comment]
So for the purposes of this ticket I completely agree - I actually don't
think auto-starting on linux is particularly important for regular users.
For the Pi and VPSes it is super important though, so maybe a second ticket
for that?
