### ISSUE TITLE
Suspected new behaviour of blocking

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2370]
Seen on Windows 8.1 as well as Mac. It's not ECONNRESET but EOF.

> Apr 09 02:53:43.146 - detour: Error while read from www.youtube.com:80 initially: EOF
> Apr 09 02:53:43.660 - detour: Error while read from www.youtube.com:80 initially: EOF

> Apr 09 03:02:17.204 - detour: Error while read from www.facebook.com:443 initially: EOF
> Apr 09 03:02:17.872 - detour: Error while read from www.facebook.com:443 initially: EOF

**Comment by myleshorton** [comment]
Does detour currently handle that case @fffw?

**Comment by fffw** [comment]
@myleshorton Might caused by my local network. Didn't see it today. I'll keep looking at it.

**Comment by myleshorton** [comment]
Ha interesting. I believe I was also seeing EOF when my local network was
flaky, so that would make sense.

On Thu, Apr 9, 2015 at 9:34 PM, fffw <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> Might caused by my local
> network. Didn't see it today. I'll keep looking at it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2370#issuecomment-91426124>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
The actual error doesn't matter anymore. Detour logic checks all network errors.
