### ISSUE TITLE
Bad response status for read: 409 Conflict

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2501]
It was only seen since May 9th. An example of full message:

> fronted: masquerade.go:160 HTTP ERROR FOR MASQUERADE torlock.com: Head http://www.google.com/humans.txt: Dest: www.google.com:80 ProxyHost: Unable to issue write request: Bad response status for read: 409 Conflict

**Comment by aranhoide** [comment]
Did you see this in loggly or in your own testing?  I get lots of these if I use `jp.fallbacks.getiantem.org` as my frontedserver.  But if this only happened since May 9th it may be related to @sheena3's testing of the Tokyo datacenters from India.

**Comment by aranhoide** [comment]
This should be fixed now.  For future reference, this is what it looks like when the fronting round robin we use has no servers registered to it.  I'll close this as soon as @sheena3 confirms that Tokyo works for her.

**Comment by fffw** [comment]
Yes, it stopped reporting on Loggly. I didn't see any such logs locally either. Closing.

**Comment by atavism** [comment]
I'm seeing this again? There were 1,666 new instances of this event in Loggly for the new beta since yesterday.

**Comment by myleshorton** [comment]
Damn. Something's screwed up with DNS. Any consistency in terms of where
the reports are coming from?

**Comment by aranhoide** [comment]
DNS resolution in the Tokyo datacenter is broken altogether.  Vultr is doing an upgrade to their routing infrastructure tomorrow.  Let's hope that fixes it.  In the meanwhile, I've renamed the 'cloud.cn.yaml.gz' to 'cloud.cn.yaml.gz.disabled' so users in China will get the default (i.e. Amsterdam) config.

**Comment by aranhoide** [comment]
But that raises the question of how will Chinese users get the updated config.  This argues for adding the overall 'roundrobin.getiantem.org' as a fallback at least, with minimal weight.

**Comment by aranhoide** [comment]
OK, I could fix DNS in one of these servers by just adding the Google nameservers to `/etc/resolvconf/resolv.conf.d/base` and then calling `resolvconf -u`.  I'll apply this hotfix to all servers in Tokyo, for the benefit of users stuck with an old cloud.cn.yaml.gz.  Then we can decide whether to reenable this generally.

**Comment by aranhoide** [comment]
OK, once I hotfixed DNS as explained above, some `jp.fallbacks` DNS entries started trickling in to Cloudflare, so we should we good even for users stuck with a 'cn' config.  IIUC this should only affect early testers anyway, since beta5 included the change to remove client-side handling of per-country configuration.

Unless someone asks otherwise, I'll leave the cloud.cn.yaml.gz disabled until after the Vultr upgrade tomorrow.

Please reopen if this keeps showing up or you observe any possibly related issues.

**Comment by xiam** [comment]
Starting to see this again in beta5 logs.

**Comment by aranhoide** [comment]
@xiam : note that this was last spotted in beta5 logs.  I fixed this yesterday So it's normal that these still crop up in our last-2-days summary.  Since I see a bunch of jp.fallbacks entries in Cloudflare right now, I'm going to assume that these logs are from before fixing this.  I'll check loggly tomorrow, and if I see none of these for the last 24h I'll close this.

**Comment by xiam** [comment]
Oh, thanks for the clarification @aranhoide!

**Comment by myleshorton** [comment]
I'm not seeing this at all -- moving to beta 7 in case it re-appears.

**Comment by aranhoide** [comment]
We got some 409s recently but it was a different problem which I'll report separately.
