### ISSUE TITLE
Welcome screen on FF on Ubuntu not appearing correctly

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2509]
![image](https://cloud.githubusercontent.com/assets/1143966/7598534/ba83743c-f8af-11e4-831c-1602f016c61e.png)

**Comment by myleshorton** [comment]
@fffw might make sense to look at this one too while you're in the general area.

**Comment by fffw** [comment]
Below is the screen of Lantern running on FF and Ubuntu 14.14. Binary is built from branch `issue2496`. Your binary may be built from an old commit, as the twitter image is a square, now it becomes rounded square.

![image](https://cloud.githubusercontent.com/assets/10410437/7605086/21ac778e-f97e-11e4-9084-c8ea779f45e5.png)

**Comment by myleshorton** [comment]
Interesting -- looks fine to me on valencia but not from built version -- could be something wrong with the build process. Did you run from the deb or from source @fffw?

**Comment by fffw** [comment]
@myleshorton I was running the one built through `make linux` under issue2496 branch. I tried valencia branch (with issue2496 merged in), same result.

The Facebook button is still very slow sometimes though, but maybe due to the response time of FB itself. In my test, http://connect.facebook.net/en_US/sdk.js takes 1 min, the script loaded by it takes another 1.8min.
