### ISSUE TITLE
Lantern thinks cloud config is always a new version

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2568]
Not sure if it's because the new config isn't honoring the etag, but Lantern thinks the config is updated every time now.

**Comment by aranhoide** [comment]
There are two problems here, one of which I don't fully understand.

First, the client is never sending any headers (or, incidentally, body, but I don't suppose we're using this for anything) in direct requests.  These are left behind [here](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/fronted/dialer.go#L211).  Only the request URL is copied over.

But even once we fix that there's a more befuddling one.  The client never sees any ETag in the response headers of the config request.  If I try direct domain fronting with curl to a server I set up:

    curl -i -k -H "If-None-Match: my-etag" -H "Host: config-test.getiantem.org" https://198.41.16/cloud.yaml.gz

I get this in the response

    Etag: thisisanetag
    Someotherheader: thisisanotherheader

(these headers are set unconditionally).  But if I modify [this line](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/config/config.go#L225) in the Lantern client to

```go
		cfg.CloudConfig = "https://config-test.getiantem.org/cloud.yaml.gz"
```

...and I print out the headers in the response when the client is trying to update its config, then I get no Etag (but I do get Someotherheader).

I couldn't find anywhere where our implementation of DDF would mess with the response, or anything in our request that could cause Cloudflare to strip the Etag itself.

A workaround for this would be to just use a custom header instead of ETag for this.  I think this is a sane thing to do anyway if we're serving this dynamically, because if we ever need to switch to other CDNs they are bound to do funny things with standard headers like ETag too.  

We'll need to release a fix for the (first) error described above anyway, so when the config server is ready should I just change the etag constant in config/config.go to something like X-Lantern-Etag and be done with it?

**Comment by aranhoide** [comment]
While the 'If-None-Match' header makes it to the server alright, maybe I might as well change that one for a custom one too.

**Comment by myleshorton** [comment]
Yeah the custom headers sound good to me - great digging over there!

**Comment by myleshorton** [comment]
@aranhoide you could also always use the Last-Modified and If-Modified-Since headers if those make it through.

**Comment by myleshorton** [comment]
Is this all set with your latest changes @aranhoide?

**Comment by aranhoide** [comment]
Yes, as soon as the config server is deployed.  I've found a bug when deploying it that didn't happen in my manual testing, so I reverted config.getiantem.org to point to the static S3 site and I'm now debugging this.

Anyway, since nothing more is needed specifically for this issue, I'll close it.  Let's reopen if it happens again after deploying the config server.
