### ISSUE TITLE
Lantern is using two different directories for logs and settings

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2604]
I deleted both directories and they reappeared again after running Lantern

```
lantern@vagrant:~$ find .Lantern/
.Lantern/
.Lantern/logs
.Lantern/logs/lantern.log
lantern@vagrant:~$ find .lantern/
.lantern/
.lantern/lantern.yaml
lantern@vagrant:~$
```

**Comment by myleshorton** [comment]
Ah yes. I would probably fix this in appdir itself instead of externally (i.e. just lowercase on linux).

**Comment by sheena3** [comment]
This works fine now. I am getting only .lantern folder after I deleted the .Lantern folder.

FYI - If I am just updating then it doesn't delete .Lantern folder by default. However, I am not seeing any problem with that now because only the .lantern folder gets updated and not the .Lantern folder. I think it should be fine. It will just sit idle in the User's machine :)
