### ISSUE TITLE
Lantern stops working if it can't access nl.fallbacks.getiantem.org and it has no trusted chained servers

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2622]
I'm opening the issue so we can discuss if this is an actual problem.

How to replicate:

1. Delete current `lantern.yaml`
2. Start Lantern, wait some seconds and then `^C` it.
3. Open `lantern.yaml` and change the `frontedservers` section to `frontedservers: []`
4. Replace all occurrences of `trusted: true` to `trusted: false`
5. Start Lantern and try to proxy something.

Lantern starts failing with 500 errors like:

```
curl -x 127.0.0.1:8787 http://www.google.com/humans.txt --verbose
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8787 (#0)
> GET http://www.google.com/humans.txt HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.google.com
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 09 Jun 2015 22:52:19 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 127.0.0.1 left intact
```

I think that Lantern should be smart enough to try a hardcoded fallback when no configured fallback is found. Lantern could also try to repair a bad config file, when we delete the old one a new one is generated so it must be possible to repair or replace the tampered one.

**Comment by xiam** [comment]
Lantern probably should also try detour when nothing else works.

**Comment by aranhoide** [comment]
What's the bug exactly?  This is expected behavior.  If you don't have any trusted proxies you can't proxy to a plain HTTP site.

I think at some point it used to be the case that the client would make sure that _some_ fronted server was available, by restoring the hardcoded one if the loaded configuration had none.  IIRC we disabled that so we could disable fronting to test chained servers.  I think that rationale remains valid.  lantern.yaml is a development and troubleshooting aid, not an interface for end users.

There are countless ways users could get themselves in trouble by messing with it.  This doesn't even seem the most likely one.  Anyway, I think any time worrying about users messing with their lantern.yaml would be best spent elsewhere.  I'd rather not save the configuration to disk at all than have to anticipate all the ways users could mess it up.

IIUC detour is about detecting blocked servers not in the whitelist so they'll get proxied through the usual means.  It is not, in itself, a proxying method, right?

**Comment by xiam** [comment]
> What's the bug exactly? This is expected behavior. If you don't have any trusted proxies you can't proxy to a plain HTTP site.

The problem I see is that Lantern just gives up, it does not even try to use its initial hardcoded settings (the settings it uses when no lantern.yaml is present) when everything else fails. It just returns 500 errors and refuses to continue working.

> There are countless ways users could get themselves in trouble by messing with it.

My point is not on the config file, I messed with it on order to simulate a situation in which Lantern is left without any methods of access. 

> IIUC detour is about detecting blocked servers not in the whitelist so they'll get proxied through the usual means. It is not, in itself, a proxying method, right?

You're right detour is not a proxying method. AFAIK, if the "Proxy all" setting is turned off, detour tries to access sites directly except that in this case it didn't work.

**Comment by aranhoide** [comment]
> My point is not on the config file, I messed with it on order to simulate a situation in which Lantern is left without any methods of access.

And you were able to successfully simulate that scenario because the config server didn't try to second guess you.  ;)

If your point is that Lantern should (for example) fall back on the Amsterdam servers for Chinese users if the Tokyo ones stop working, that's a valid one.  But I think we should implement that by just having the global round robin as a last resource in both the builtin and cloud configurations (for example, give it a tiny weight and low QOS so it won't be selected if anything else works).

> AFAIK, if the "Proxy all" setting is turned off, detour tries to access sites directly except that in this case it didn't work.

You were trying to access google.com, which is in the whitelist.  I don't think detour is ever supposed to try and directly access sites in the whitelist, but I could be wrong.

More generally, I think we have a policy of not attempting to access directly sites that we believe to be blocked, because that could get users in various sorts of trouble.  If Lantern is so broken that direct access is preferrable, I expect users will close it quickly, and I think that's the least confusing way to fall back on direct access.

**Comment by myleshorton** [comment]
Yeah I tend to agree with @aranhoide here. Lantern should have as many fallback options as possible, but I would for example strongly preference making sure Lantern works if only one of chained proxies and domain fronted proxies stays up (#2623 and #2609) over this, which to me seems more like a misconfiguration bug on our end.

**Comment by xiam** [comment]
Thanks for the review @aranhoide, @myleshorton, let's close this one then.
