### ISSUE TITLE
Lantern beta 4 opens up on system startup instead of beta 6

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2639]
I have installed Lantern beta 4, beta 5 and beta 6 in Mac. I modified settings in Lantern beta 6 to open on system startup.

After restarting the system, beta 4 opens up instead of beta 6. It doesn't look like a big issue to me but would be great to always open the latest version available in the system.

**Comment by fffw** [comment]
Yeah that's because we use fixed path "/Applications/Lantern" in launcher
file. If we choose "Keep Both" during installation, the newly installed
version will be placed at "/Applications/Lantern 2", "/Applications/Lantern
3"...

Has anyone ever kept both version of same software installed? I think we
can keep it as is until user complains.

**Comment by myleshorton** [comment]
Yeah I agree @fffw. I assume you chose "keep both" is that right @sheena3?

**Comment by myleshorton** [comment]
Closing this since it should be a rare case...

**Comment by sheena3** [comment]
Am sorry for not responding to this before. Yeah @myleshorton , I chose "Keep both" option.
