### ISSUE TITLE
Make client side recover from server failures

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2695]
The Lantern client should automatically re-request resources when a server fails. This is particularly important for p2p servers that are more likely to disappear at faster rates.

**Comment by myleshorton** [comment]
@uaalto I think this ticket will really be necessary for the initial p2p implementation.

**Comment by uaalto** [comment]
Got it!

**Comment by uaalto** [comment]
@myleshorton I need a couple of things to understand what we want to achieve here:

* What would be the trigger? i.e. what makes flashlight client decide a server (both chained and fronted?) has failed.
* Once this is decided, we re-download and apply the config.yaml?

**Comment by myleshorton** [comment]
> What would be the trigger? i.e. what makes flashlight client decide a server (both chained and fronted?) has failed.

The trigger would just be a failure successfully getting an HTTP response for a given request.

> Once this is decided, we re-download and apply the config.yaml?

No, we'd just try the request with a different server.

We'd probably only want to do the above retry procedure 3 times or so I imagine.

**Comment by uaalto** [comment]
OK, thanks!

**Comment by uaalto** [comment]
Getting some background on the code where this needs to be implemented:

* We are only concerned with `intercept` (in https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/handler.go#L38), because direct proxying can only be done with HTTP, and we don't want to do that for P2P. Or should we implement this also for the HTTP case so it can be used with direct proxying?
* Currently, `balancer` takes care of retrying TCP connections with different `Dialer`s if they fail to connect. Therefore, connection retries at the TCP level are already solved by balancer, so we are concerned primarily by what happens after the proxy replies `200 OK`.
* The process, as it stands at the moment is: 1) The proxy client sends a `HTTP CONNECT` request to the proxy server. 2) The proxy server replies with `200 OK` to the client. 3) The client starts bidirectionally piping raw TCP data to the proxy server, which is able to handle it because that raw data is actually an HTTP message.
* This means that we are currently treating the post-OK HTTP messages as raw TCP being passed from client to end-point. If we want to be able to retry those HTTP requests, we need to replay [this](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/handler.go#L79) request, which would be failing [here](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/handler.go#L120).

Failure scenarios, after the `200 OK` response has been received to the `HTTP CONNECT` request:

* I the server failure happened during the request, it can be just replayed.
* If the server failure happened while the response was already initiated, we need to figure out what to do.

Some options for _when the response was already initiated_:

* Record byte transferred, and then re-issue an HTTP request with the `Range` header field. This would work if supported by the browser and if our client connection doesn't timeout.
* Buffer everything until we have the response body completed, and then pipe it to the client connection. This doesn't sound like a good idea for two potential problems: possible delay and the size of some requests (although this second problem could be reduced by setting a max size for which to apply this technique).
* Simply close the connection and do not handle it, as if the endpoint caused this behavior.

**Comment by uaalto** [comment]
WIP [here](https://github.com/getlantern/lantern/tree/issue-2695)

**Comment by myleshorton** [comment]
Hey @uaalto I'm finally just now getting to this. Sorry for the delay again! I'm actually wondering if this is really feasible. As you point out, we only send HTTPS traffic to peers, which means we can't resume in the middle. As a result, this is only useful if the connection drops immediately after initially connecting and before any data is transferred, which is a very limited case.

So I actually think we should just close this after all. The tricky case is really for large files, but maybe in the future we can do something fancier there like use a browser extension to capture initial HTTP responses and do things like break up big ones or maybe redirect big responses so they don't go through peers.

**Comment by uaalto** [comment]
Thanks @myleshorton !

Some speculation here:

1. We can still implement the case where the connection fails during the request, prior to receiving any bytes, and just restart it. This would bring more resilience I think.

2. Even though we can't resume connections, we can use a Range header field and request a partial file even in HTTPS, with a new connection. Flashlight-client would isolate the client software from any connection drops to the Flashlight peer and the target. Flashlight-client could ask a new peer to initiate a range request with the target (a new TLS handshake). This should work for large file downloads.

3. The next step (the biggest challenge), is TLS sessions and multiple requests over the same connection. I wonder if we can somehow use TLS sessions to re-initiate the TLS connection from another server just using the session ticket (session resumption). I think, theoretically, it could work. Session resumption should only check the ticket. But I'm not sure at all about that. If things like IP are checked too, and stored in the ticket, we can't. Besides, the target needs to support session tickets.

**Comment by uaalto** [comment]
This seems interesting: https://tools.ietf.org/html/rfc4507#section-5.2

**Comment by myleshorton** [comment]
> We can still implement the case where the connection fails during the request, prior to receiving any bytes, and just restart it. This would bring more resilience I think.

Yeah I think that makes sense, and it could be particularly useful in the case of large uploads -- like maybe we could redirect the request to the same place or some trick like that if things fail during an upload.



> Even though we can't resume connections, we can use a Range header field and request a partial file even in HTTPS, with a new connection. Flashlight-client would isolate the client software from any connection drops to the Flashlight peer and the target. Flashlight-client could ask a new peer to initiate a range request with the target (a new TLS handshake). This should work for large file downloads.

Yeah that's interesting. I think the problem, though, is having a place to plug the Range header in. We don't see any of this raw data, and we don't have access to the HTTP headers, because it's all over HTTPS. I *think* we would need something like a browser extension that can actually manipulate the underlying headers in order to do that unless I'm missing something. I think long term doing things like that with a cooperating browser extension could be a really nice addition, but it seems like overkill for where we're currently at.

> The next step (the biggest challenge), is TLS sessions and multiple requests over the same connection. I wonder if we can somehow use TLS sessions to re-initiate the TLS connection from another server just using the session ticket (session resumption). I think, theoretically, it could work. Session resumption should only check the ticket. But I'm not sure at all about that. If things like IP are checked too, and stored in the ticket, we can't. Besides, the target needs to support session tickets.

We already use a [TLS session cache](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/chained.go#L59) but I don't think we can do that across servers can we? In terms of the browser connection itself, it's also the browser that has the ticket and not us, so I again think we might need something on the browser side to really take advantage of that.

**Comment by uaalto** [comment]
Yes, I didn't realize that the Flashlight client can't see the contents. We are tunneling raw data from origin to target when we use CONNECT. So we have to sit at the origin (ie browser) to do this. I completely agree is something for the future. Super exciting stuff though!

I think the way to do this would be that the flashlight peer does the https connection on behalf of the user, contrary to using CONNECT. This comes with a share of complexities of course, and is a large change, even conceptually. But I've done a little research and I think is possible, kind of a legal MITM.

On the TLS session cache side, I think we actually can use that across servers if we carry keys along the tickets too (low-level hacking I guess). These needs real testing, but taking a look at the RFC appears possible. I'm still unclear if we could benefit from that in the current scenario though.

The code I've been working on already transparently retries failed requests with zero response bytes. I'll test it a bit more and see if it works and is worthy of review, does it sound good?

**Comment by uaalto** [comment]
Second paragraph: _I think the way to do this would be_ --> _Another way to do this_

**Comment by myleshorton** [comment]
Clients current try 3 times regardless of the server and will keep servers in rotation thereafter with lower priority.
