### ISSUE TITLE
how to use cloudfare CDN to speed lantern node?

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2724]
Hi,
how to use cloudfare CDN to speed lantern node? I'm in China, the lantern speed is very slow , I want to use cloudfare CDN to speed lantern node, then how can I do ?

**Comment by myleshorton** [comment]
Hi @yuan78 thanks for reaching out. Unfortunately CloudFlare won't speed anything up for you but will add another layer that traffic gets sent through, so it would actually slow things down. CloudFlare speeds things up *when it acts as a CDN for ordinary web sites* because it caches copies of sites closer to where you are. But it can't do that for general proxying, so it would slow Lantern down.

What version of Lantern are you using? Is it using servers in Tokyo?
