### ISSUE TITLE
Lantern documentation project

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2727]
This is project in which @uaalto will also participate. Documentation will help us to fully describe Lantern from a purely technical standpoint. This documentation is for developers but could be used later for writing a manual for end users.

I opened this thread to discuss what should we document. There is some existing documentation but it is not in a central repository, we should use the existent documentation whenever possible.

**Comment by uaalto** [comment]
Great! 

I propose the following basic structure, in a nutshell:
* Main README.md with a description of the different services and programs that comprise the Lantern ecosystem (i.e. peerscanner, chained proxy, etc..). Each project will have a short description that conveys *what* it does, not *how*. That will be the mission of a README in each each one of the projects, linked in its section of this main README.
* Follow this by the linked README.md's of each one of those projects. These READMEs will start with a general description, and then dive into deeper details, technical decisions and some background where applicable.

Also, I wanted to take this chance to mention that it will be great to document and discuss the new naming convention to each one of the parts that Estevo and I thought out in L.A. It became apparent that this convention was important as soon as we started working on P2P, since it blurs the line between servers/clients and we need proper definitions. I can document that myself to kickstart this documentation project.

**Comment by uaalto** [comment]
WIP [here](https://github.com/getlantern/lantern/tree/issue-2727)
