### ISSUE TITLE
How to show worldmap when lantern start if modify the source code and build binary from git repo?

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2772]
Hi,
How to show worldmap when lantern start by modifying the source code and building binary from git repo?

which file of souce code shall I modify, is it UI.go, and how to modify it? THX!

**Comment by uaalto** [comment]
Hi yuan78. We decided to remove the UI map because didn't find it conveying any useful information to users at the moment. Moreover, it was confusing to many users.
Why do you want it back? Was it useful to you or you liked the UI?
It is possible that we are bringing a new and similar UI back for give mode, but that is work in progress.

**Comment by myleshorton** [comment]
This shouldn't be too difficult @yuan78. Reverting back to commit 25603dbdb3ec60c2f4f484e9c8961581c1a3b90b in lantern-ui should do. Then you can build with:

UPDATE_DIST=true VERSION=2.0.0-beta8 make packages

or depending on your OS:

UPDATE_DIST=true VERSION=2.0.0-beta8 make package-darwin
