### ISSUE TITLE
Never return "localhost" as an address from our config server

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2825]
Basically because of #2817 our config server returning localhost in addresses will make things like auto-update not work in a lot of cases.

Because the config itself uses direct domain fronting, however, we can still update the config in spite of #2817. That will allow us to effectively bypass #2817 by just not using "localhost" in any address the config server returns, using 127.0.0.1 instead!

**Comment by myleshorton** [comment]
Can you knock this one out @aranhoide? Will allow auto-updates to keep working.

**Comment by aranhoide** [comment]
I don't understand.  Where is the config server returning "localhost"?  Is that in the default cloud.yaml?

**Comment by myleshorton** [comment]
Well, maybe it's not returning it, which would be great. The client defaults use it at:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/config/config.go#L211

But I'm actually a little unclear on how you're generating the config on the config-server side. What's that based on exactly?

**Comment by aranhoide** [comment]
It's generated via genconfig.bash, then uploaded via cfg2redis.py.  

I just checked, and the only occurrence of "localhost" in the config for Iran (so, everyone but China) is a "localhost.com" proxied site (whitelist item).  I don't suppose the config for China introduces any more "localhost"s anywhere.

Grepping the source tree I see that "localhost" is used in some hardcoded defaults, e.g.

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/config/config.go#L211

So apparently what is needed is just a search&replace for "localhost" in the flashlight tree.

Unfortunately, this means this won't get fixed until a new release.  I could try overriding these defaults in the cloud config too, but this fix will only work if and when clients get a cloud config.  Do you want me to do that?

**Comment by myleshorton** [comment]
I already made that change to the client for 2.0.0 @aranhoide but the point of doing this on the config server is that it will overwrite those local values like we discussed on Monday. What's the status of that?

**Comment by aranhoide** [comment]
Unfortunately the servers are using the same config URL as our clients (although they're using an old codebase, their configuration in the hardcoded cloud config url has, in turn, a `cloudconfig` pointing to the new one).  We can't override `cfg.Addr` for servers, or they would stop working.  So I'll need to create a new cloud config for servers and have them use that, before hardcoding these for clients.  If this is more urgent than fixing the pegging-one-CPU problem (is it?), we'll need to override this in the command line parameter in the flashlight.conf.  Since it can't hurt to do that, I'll get to it now.
