### ISSUE TITLE
The close window button that appears in the Lantern page after quitting Lantern is not working in Firefox

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2854]
It works fine in IE and Chrome

**Comment by myleshorton** [comment]
You want to take this for a spin @atavism?

**Comment by fffw** [comment]
[window.close()](https://developer.mozilla.org/en-US/docs/Web/API/Window/close) refuses to close a window not open by script in FF, seems no workaround works. I guess it's ok to just show the message "Please close your browser tab" on FF.

**Comment by sheena3** [comment]
This is happening in Mac - Chrome too.

**Comment by atavism** [comment]
@sheena3 But it was working before for you on Chrome? How long ago?

Yeah, I looked into this as well, and I'm not sure there's a good workaround for Firefox (at least I haven't been able to find one). I think just displaying a message that Lantern went away instead is the best option for FF.

**Comment by sheena3** [comment]
Yes @atavism. Chrome works fine in windows. This issue is in Mac-chrome.

**Comment by atavism** [comment]
Thanks, @sheena3. Chrome is working for me on Mac so I'm unable to reproduce. Anyone else able to? Are you seeing anything in the Developer Tools console when you click on the button? What version of Chrome are you running?

**Comment by uaalto** [comment]
I could reproduce it. If you click on the button you'll see the following in the console:
`Scripts may not close windows that were not opened by script.`

Unfortunately, this is a feature of Firefox (and should be of others as well), rather than a bug. More details on [this thread](https://stackoverflow.com/questions/19761241/window-close-and-self-close-do-not-close-the-window-in-chrome). We cannot close that window if we didn't open it from within the same script, unless the user sets a special flag in `about:config`.

Furthermore, I tried it on Chrome and it doesn't close either. This probably happens in the rest of browser, unless they have the associated vulnerability. I think we should just remove the button and avoid unnecessary complexity/hacks.

**Comment by myleshorton** [comment]
This one's all set @atavism right?

**Comment by atavism** [comment]
@myleshorton Yep, we removed the button, and only a message is being displayed now instead.
