### ISSUE TITLE
Create a better consolidated solution for monitoring all servers

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2884]

**Comment by myleshorton** [comment]
@fffw can you just document here potential solutions for this?

**Comment by Dineshan** [comment]
I open lantern and go to youtube and begin search.  But many of the sites are reporting that it is not available in our region.

**Comment by myleshorton** [comment]
Which sites?

**Comment by fffw** [comment]
### Storage

InfluxDB is promising and works well during our test and trial. Hosted InfluxDB service would be good, but standalone server also just works. We can collect metrics to monitor itself.

### Collection

We mainly have 3 type of services in our infrastructure.

*  VPS (bunch of them and ever increasing!)

We already use salt as configuration manager. There're existing scripts running on salt clients (monitored servers) as cronjob to send alerts. There's also a script called `report_stats.py` to report stats to librato.com every 10 minutes, but I'm not sure if it is working, as the credential to librato is incorrect.

Salt also has several modules to collect metrics, but instead of adding burden to cloud master, we can run mature tool like [collectd](https://collectd.org/) on each server that continously collect and report metrics.

Together with application level data collection afterwards, we can have a sense on the correlation between them.

* Heroku applications.

A new go tool called [lumbermill](https://github.com/heroku/lumbermill) can extract metrics from Heroku logs and send to InfluxDB.

* 3rd hosted services.

Including RedisLib, BigQuery, CloudFlare, etc. `statshub` uses the first 2, so we can retire them after migrating to new solution. If the service is vital important, we can collect via its API, or we can keep our current way of manually checking.

### Presentation

Grafana is good at configure and show charts and works well with Influxdb. If we do want a more consolidate one, its UI can be easily modified, or we can craft a skeleton page which just embeds those graphs.

### Alerting

Currently we depends on scripts scattered on servers to send alert. Once we have data consolidated, we can have an organic way to set rules based on the whole picture.

Grafana alerting system is WIP, we can wait for it as well as other tools, or even customized one.

**Comment by myleshorton** [comment]
Sounds great @fffw! I would just experiment with them and try to narrow
down whatever you think is really the best.

On Tue, Aug 11, 2015 at 1:03 AM, fffw <notifications@github.com> wrote:

> Storage
>
> InfluxDB is promising and works well during our test and trial. Hosted
> InfluxDB service would be good, but standalone server also just works. We
> can collect metrics to monitor itself.
> Collection
>
> We mainly have 3 type of services in our infrastructure.
>
>    - VPS (bunch of them and ever increasing!)
>
> We already use salt as configuration manager. There're existing scripts
> running on salt clients (monitored servers) as cronjob to send alerts.
> There's also a script called report_stats.py to report stats to
> librato.com every 10 minutes, but I'm not sure if it is working, as the
> credential to librato is incorrect.
>
> Salt also has several modules to collect metrics, but instead of adding
> burden to cloud master, we can run mature tool like collectd
> <https://collectd.org/> on each server that continously collect and
> report metrics.
>
> Together with application level data collection afterwards, we can have a
> sense on the correlation between them.
>
>    - Heroku applications.
>
> A new go tool called lumbermill <https://github.com/heroku/lumbermill>
> can extract metrics from Heroku logs and send to InfluxDB.
>
>    - 3rd hosted services.
>
> Including RedisLib, BigQuery, CloudFlare, etc. statshub uses the first 2,
> so we can retire them after migrating to new solution. If the service is
> vital important, we can collect via its API, or we can keep our current way
> of manually checking.
> Presentation
>
> Grafana is good at configure and show charts and works well with Influxdb.
> If we do want a more consolidate one, its UI can be easily modified, or we
> can craft a skeleton page which just embeds those graphs.
> Alerting
>
> Currently we depends on scripts scattered on servers to send alert. Once
> we have data consolidated, we can have an organic way to set rules based on
> the whole picture.
>
> Grafana alerting system is WIP, we can wait for it as well as other tools,
> or even customized one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2884#issuecomment-129752196>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
I started with Heroku monitoring as we have a few key services on it, but didn't have performance graphs yet.

I deployed a [lumbermill](https://github.com/heroku/lumbermill) instance on Heroku, it works smoothly to process logs sent from other Heroku apps. Unfortunately it only supports InfluxDB v0.8, I'm playing around it to support v0.9.

**Comment by fffw** [comment]
Performance dashboard for Heroku applications was online and works fine. Tested running collectd on 2 DO servers and successfully have data stored in InfluxDB. InfluxDB has not implemented real "ORDER BY" yet. Without the top N query functionality, just showing graphs of hundreds of servers is useless. Next step would be to deploy it to key servers together with Alan.

**Comment by myleshorton** [comment]
Closing this with the influxdb/grafana solution in place.
