### ISSUE TITLE
panic: Unable to determine user's home directory: user: Current not implemented on android/arm

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2916]
Built a fresh copy of the library while I was working on https://github.com/getlantern/lantern-mobile/issues/3 and the app crashes immediately with the following: 

```
D/LanternMainActivity(18919): Starting Lantern...
D/dalvikvm(18919): Trying to load lib /data/app-lib/org.getlantern.lantern-34/libgojni.so 0x424ff290
W/linker  (18919): libgojni.so has text relocations. 
This is wasting memory and is a security risk. Please fix.
D/dalvikvm(18919): Added shared lib /data/app-lib/org.getlantern.lantern-34/libgojni.so 0x424ff290
D/dalvikvm(18919): No JNI_OnLoad found in 
/data/app-lib/org.getlantern.lantern-34/libgojni.so 0x424ff290, skipping init
E/Go      (18919): panic: Unable to determine user's home directory: 
user: Current not implemented on android/arm
E/Go      (18919): goroutine 1 [running]:
E/Go      (18919): github.com/getlantern/appdir.InHomeDir(0x8ad01500, 0x8, 0x0, 0x0)
````

**Comment by myleshorton** [comment]
Interesting. I'm surprised it didn't crash before - odd. Added to 2.0.1

**Comment by uaalto** [comment]
I've opened [this one](https://github.com/getlantern/lantern/issues/2908) before, which is basically this error. This is fixed in https://github.com/getlantern/lantern/pull/2910, but I have to make sure that this works well though. I assumed that it wasn't used before, because this code wasn't there before either.
