### ISSUE TITLE
Detect and report user-agent in loggly

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2925]

**Comment by uaalto** [comment]
@myleshorton thinking about this problem a bit, I think there are various ways to approach this.
The main problem is that:

* A logged error doesn't need to be associated to a specific request (general errors)
* A user can be using many simultaneous clients, and this is to be expected.

Approaches:

1. We could manually take care of logging the error with the request information, in sensitive places. This way we could associate an error with its parent request, in places where this association is meaningful. We would need to carry this information (the request itself or an identifier) and pass it as a parameter to each function. Otherwise we don't know which request is the function being called for, because of concurrency.
1. We could have a per-session global set of clients being used, so each error appends this list. The list would be updated with each new client detected. This list could also act as a (kind of) cache, removing old entries that haven't been used in 5-10 mins. or so, because they with high probability aren't linked to the issue.
1. We could do both.

I propose starting with the second, but doing a first pass of the first, adding it in the places that we've already detected that this information would be worth having.

**Comment by myleshorton** [comment]
Yeah I agree about going with the second, although I might not worry about
the cache expiry -- maybe just having it start fresh with each run of
Lantern is enough?

**Comment by uaalto** [comment]
Should be enough, yes. It's valuable information anyways, and probably an unnecessary premature optimization. Thanks!
