### ISSUE TITLE
SOCKS support

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2937]
In order to be able to redirect traffic from a [tun2socks](https://code.google.com/p/badvpn/wiki/tun2socks) virtual device Lantern needs to support a local SOCKS proxy server.

This does not have to replace our current HTTP proxy, we can just spin a SOCKS server on another port and use our current HTTP proxying capabilities.

See: https://godoc.org/golang.org/x/net/proxy

**Comment by uaalto** [comment]
Nice @xiam! I used [this library (shadowsocks)](https://github.com/shadowsocks/shadowsocks-go), stripping out some of its code for doing a SOCKS proxy. I did just a toy program, but that library is solid.

**Comment by myleshorton** [comment]
Cool guys. I think @atavism is working on changing tun2socks to send to
HTTP CONNECT instead, is that right @atavism? Then again the simplest
solution might just be a SOCKS proxy in go that sends everything over HTTP
CONNECT on the backend.

Very cool there's a go port of shadowsocks. Interesting!

On Thu, Aug 13, 2015 at 9:17 AM, Ulysses Aalto <notifications@github.com>
wrote:

> Nice @xiam <https://github.com/xiam>! I used this library (shadowsocks)
> <https://github.com/shadowsocks/shadowsocks-go>, stripping out some of
> its code for doing a SOCKS proxy. I did just a toy program, but that
> library is solid.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2937#issuecomment-130747047>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by uaalto** [comment]
Yes, if I recall properly, SOCKS just works as a tunneling setup protocol, and then you can tunnel whatever you want (just relays data).

**Comment by atavism** [comment]
I think we should explore multiple solutions. What I'm doing first is forking our own copy of tun2socks so that it's even possible for us to make customizations.

The biggest issue to me is with Android's VPNService, you have to mark sockets "protected" in order to route them outside the VPN at all, meaning any connection Lantern makes, we need some way to track it on the Java-side and protect the underlying socket, IIUC. This is why Orbot uses a local SOCKS proxy written in Java. I think just doing it on the tun2socks side might make everything easier.
