### ISSUE TITLE
file damamaged found in 2.0.0-beta+manoto, update_darwin_amd64.bz2 

### ISSUE THREAD

**Issue by certainly** [getlantern/lantern#2946]
https://github.com/getlantern/lantern/releases/download/2.0.0-beta8%2Bmanoto/update_darwin_amd64.bz2

I download this file , unzip it ,chmod+x, open it, then system alerts the file is damaged. Am I alone with this?

**Comment by fffw** [comment]
The link you posted is an update diff, not an installer. Please try following link instead to download Mac installer.

https://s3.amazonaws.com/lantern/lantern-installer.dmg
or
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.dmg

It does make user confusing, as developers are accustomed to download from release page. I think we can:
1. Add download link at the very top of README.md.
2. Add installers to each release. Auto-update server  [will not count it as update assets](https://github.com/getlantern/autoupdate-server/blob/master/server/github.go#L14)

@myleshorton @xiam How do you think?

BTW, since we released 2.0.0, the [Lantern-Beta-Versions page](https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions) should also be updated.

**Comment by certainly** [comment]
thx for your reply. now i see . As I don't have a vpn, I can't compile the source code. 
Anyway, I can wait for the next executable version release. pls close this issue

**Comment by myleshorton** [comment]
Thanks @certainly!
