### ISSUE TITLE
when install lantern on windows 10 , the antivirus report virus

### ISSUE THREAD

**Issue by ledkk** [getlantern/lantern#3018]

**Comment by cybort** [comment]
You can choose to allow it run.

**Comment by celeron533** [comment]
Sometimes, 'man-in-the-middle' could replace the binary file when downloading. You should check the MD5 first.

**Comment by ledkk** [comment]
@cybort  does you know the reason

**Comment by blacksheep061** [comment]
@ledkk I got the same problem here. Which antivirus software are you using?

I'm using Kaspersky Internet Security 15.0.0.463(b) on win7.

The antivirus software flags the installer file 'lantern-installer-beta.exe' as unknown threat __UDS:DangerousObject.Multi.generic__. Also, the antivirus software automatically deletes the installer file as soon as downloading is completed, it does not allow this particular file to be added to exception list, nor can I check the MD5 when antivirus software is in use. I got a different MD5 every time! Probably because AV interferencing with MD5 checking process.

I can, however force install lantern software if I download the installer with AV disabled. But as soon as the AV comes back online, both installer and installed binary got killed.

Btw I download lantern installer using torbrowser, since I can't reach their website behind censorship.

**Comment by myleshorton** [comment]
We'll look at this guys. Are you still experiencing that issue @blacksheep061? Sometimes things like that can be the result of AV not having seen many copies of the binary, but some AV also doesn't like that we have UPnP and NAT-PMP capabilities.

**Comment by blacksheep061** [comment]
Ok. Now my antivirus software no longer flags lantern-installer-beta.exe as
an unknown threat.

However, I still can't use lantern, this new version 2.0.6(20150915.042827)
seems to lack the old network connection map feature, when I run lantern
software, a browser window pop up and I got taken to http://127.0.0.1:16823/,
right click on the lantern icon on windows task bar and select show lantern
yield the same result. The only configuration I found is a gear shaped tiny
setting icon at the bottom-right corner of the browser window, click the
icon brings up a setting panel with only three options:Run lantern on start
up,proxy all traffic and send report.
Also, from this browser window, non of the blocked websites are accessible.

Sorry to bother you with this detailed description, but where are all those
old features such as connection map, website proxy listing and so on? Am I
doing something wrong while installing? Or did I download the authentic
installer?

I got this lantern-installer-beta.exe from
https://s3.amazonaws.com/lantern/lantern-installer-beta.exe, this file is
signed by Brave New Software Project, Inc with a fingerprint f8 a4 45 38 0e
d3 71 e3 7b df b1 05 7f 45 dc fc 0f 79 87 11.

A heart felt thanks to you hardworking guys on lantern team, I hope to
hearing from you soon.

2015-08-28 18:47 GMT+00:00 myleshorton <notifications@github.com>:

**Comment by fffw** [comment]
@blacksheep061 What you saw is exactly the UI of Lantern 2. It removed network map, proxied site list, etc., to provide a simpler UI. Lantern 2 detects blocked sites automatically so you don't need to maintain customized list any more.

To investigate why Lantern 2.0.6 doesn't work for you, could you send a copy of logs to fffw@getlantern.org? It is under `<your home folder>\AppData\Roaming\Lantern\logs`. `AppData` is a hidden folder so you may need to change Explorer settings.

**Comment by blacksheep061** [comment]
Ok. Here's the log file you requested. Please take a look. Thank you
for your persistence in this matter.

2015-09-16 1:57 GMT, fffw <notifications@github.com>:

**Comment by myleshorton** [comment]
This should be all set, as we know automatically report new versions to Kaspersky and manually report them to all other available AV channels.
