### ISSUE TITLE
Why we don't have to invite friends on lantern 2.0?

### ISSUE THREAD

**Issue by hitalex** [getlantern/lantern#3030]
In the new version of lantern (v2.0), it seems that users don't have to invite friends who are not blocked to use lantern (which is good), but why? I assume the underlying working mechanism of lantern does not change. 

Is that because all lantern users quietly become "friends" once they are using lantern?

**Comment by uaalto** [comment]
Hi @hitalex 
The reason we don't need to add friends is because Lantern is not working through a P2P infrastructure now, but through our own servers. We are planning on adding this method back. Then it might become necessary again, but we are trying also to keep it as simple to use as possible. We aren't going to add friends quietly though.
Our primary concern is providing speed to our users, so that's why we are always trying new methods of improving user's experience. However, stay tuned for the P2P come back!

**Comment by hitalex** [comment]
@uaalto : Cool! Lantern is now indeed simpler and faster than before. But servers cost money and I don't think you guys are doing charity. So I wonder: 1) is it possible that Lantern users will pay for the service? 2) if Lantern is not based on P2P, its IP will soon get banned, unless you invent new kinds of VPN-like technologies.

**Comment by uaalto** [comment]
@hitalex, at the moment we are able to provide with the service, and we will continue to do so. Lantern is using different techniques to avoid blocking, although it still can happen of course. We are trying to innovate and strengthen our methods,and among other things we are working towards a P2P-based approach.

**Comment by hitalex** [comment]
@uaalto : To my limited knowledge, a P2P based approach is probably the BEST approach to avoid blocking. Thanks for your hard work and good luck.
