### ISSUE TITLE
CloudFlare mistakenly protecting from DDOS

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3071]

**Comment by myleshorton** [comment]
The fact that this test succeeds:

https://github.com/getlantern/lantern/blob/issue3071/src/github.com/getlantern/geolookup/geolookup_test.go

while this one fails:

https://github.com/getlantern/lantern/blob/issue3071/src/github.com/getlantern/flashlight/geolookup/geolookup_test.go

is fascinating. Is it possible there actually is different protection happening for different subdomains? What do you think @fffw and @aranhoide?

**Comment by fffw** [comment]
`go test` on both encounters 403 error and runs infinitely. Regarding the difference, `getlantern/geolookup` is checking against `geo.getiantem.org`, while `flashlight/geolookup` is against `nl.fallbacks.getiantem.org`. Possible causes:

1. `geo.getiantem.org` is accessed far less frequently than `nl.fallbacks.getiantem.org` which didn't reach the CF threshold.

2. `geo.getiantem.org` looks more like a normal web site while `nl.fallbacks.getiantem.org` looks unusual to CF.

1 is more likely the truth. We may need to upgrade plan or stop using domain fronting for any user traffic. I'm curious about meek's traffic per day.

**Comment by fffw** [comment]
Oh sorry my hypothesis is totally wrong considering the test @aranhoide just run. A new account / domain also returns 403.

**Comment by myleshorton** [comment]
> go test on both encounters 403 error and runs infinitely

You get a 403 for the first test? It's odd that it would continue to run indefinitely after the 403. For me the first test succeeds, so apparently CF views our two IPs differently. Does the first test succeed for you @aranhoide? If both fail for you with a 403, then I'm not really sure it succeeding for me is useful other than maybe reflecting different handling of different IPs and/or countries.

**Comment by fffw** [comment]
403 is triggered during masquerades verification. Both tests use `fallbacks.getiantem.org` as the server behind CF, so there should be no difference. Indeed I'm curious why your test result differs.

`NewDirectDomainFronter` will never return until there's a verified masquerade, that's why tests run indefinitely.

**Comment by fffw** [comment]
After I merged my PR (verification using direct domain fronting) into your changes, tests of `getlantern/geolookup` succeeded and `flashlight/geolookup` failed with 403 which is expected.

When I run it on the Chinese box again, masquerade verification fails frequently due to time out. 1 - 3 successful runs followed by infinite time outs, regardless of which test I'm running, then recovers several minutes later. It must being interfered by the censor.

**Comment by myleshorton** [comment]
That's very interesting @fffw. You ran the tests from my issue3071 branch right? The only difference as far as I can tell is the actual request itself.

Oh, I forgot to mention I locally did disable masquerade checks, so maybe that's part of it. I also disabled the connection pool, which could affect things. Still investigating...

**Comment by myleshorton** [comment]
Oh, also, I believe the Host parameter in those tests @fffw (the "fallbacks.getiantem.org") actually doesn't matter at all because we're using direct fronting. So that can actually be anything in there -- it's completely ignored.

**Comment by myleshorton** [comment]
I think disabling the connection pool is a no-brainer by the way.
