### ISSUE TITLE
Can you add an option about the auto-update?

### ISSUE THREAD

**Issue by zhanxiage233** [getlantern/lantern#3114]
Sometimes the update did not work well to everyone, then what about add an option about the auto-update? So we can choose to update or not.

**Comment by oxtoacart** [comment]
@myleshorton We talked about this today.  My opinion is that the benefits of making sure everyone is running recent versions of Lantern outweigh the risks of a specific release having a problem.  Rather than allowing auto-updates to be disabled, it's better for us to just continue making sure we're putting out high quality builds.  Especially since we have a beta phase before we release for auto-update, I think we're in pretty good shape there.  What do you think?

**Comment by myleshorton** [comment]
Yeah honestly @oxtoacart I'm torn on this one between giving users what they want and fixing our processes to avoid this happening. Chrome is the closest example to me. Occasionally quite frankly Chrome updates seem to break things, but overall it's a tremendous benefit. They also make it quite hard to disable updates (registry setting on windows, for example), so overall I think we should continue emulating their model and should not allow users to disable it. Closing!
