### ISSUE TITLE
Currently, Lantern 2.0.5 can't work in China again.

### ISSUE THREAD

**Issue by lixiaodongsql** [getlantern/lantern#3125]
Hello. Currently, Lantern 2.0.5 can't work in China again. Error accessing page displays in my browser again. My browser shows that Lantern could not access the server at a URL.
I upload my Lantern log file to Google Group Lantern Developers.
https://groups.google.com/forum/#!topic/lantern-devel/_RrR1ddKRu4

Is the cloud platform which supports domain fronting technology and which is used by Lantern disturbed on and off by China's firewall?
Could you please help me solve this problem? Thank you very much for your help. I really appreciate it.

**Comment by cmdlet1** [comment]
where can i download Lantern 2.0.5,thx

**Comment by lixiaodongsql** [comment]
I downloaded the installation file of Lantern 2.0.5 software from the URL below.

https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe

**Comment by fulljump** [comment]
I aways can not used it in china

**Comment by fulljump** [comment]
mybe have some interference by gfw

**Comment by fulljump** [comment]
Sep 11 05:46:22.392 - 1m2s ERROR fronted: masquerade.go:169 HTTP error for masquerade www.nomadicmatt.com: Head http://www.google.com/humans.txt: Dest: www.google.com:80    ProxyHost:     Unable to issue write request: Bad response status for read from fronting provider: HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 177
Content-Type: text/html
Date: Fri, 11 Sep 2015 05:45:24 GMT
Server: cloudflare-nginx

<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

Sep 11 05:46:22.455 - 1m2s ERROR fronted: masquerade.go:169 HTTP error for masquerade videoyoum7.com: Head http://www.google.com/humans.txt: Dest: www.google.com:80    ProxyHost:     Unable to issue write request: Bad response status for read from fronting provider: HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 177
Content-Type: text/html
Date: Fri, 11 Sep 2015 05:45:24 GMT
Server: cloudflare-nginx

<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

Sep 11 05:46:22.835 - 1m2s ERROR balancer: balancer.go:100 Unable to dial via (trusted) chained proxy at 178.62.234.129:443 to tcp://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 178.62.234.129:443: dial tcp 178.62.234.129:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 1...continuing
Sep 11 05:46:29.326 - 1m9s ERROR balancer: balancer.go:100 Unable to dial via (trusted) chained proxy at 178.62.213.97:443 to tcp://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 178.62.213.97:443: dial tcp 178.62.213.97:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 11 05:46:34.323 - 1m14s ERROR fronted: masquerade.go:169 Timed out verifying haber1903.com
Sep 11 05:46:36.153 - 1m16s ERROR balancer: balancer.go:100 Unable to dial via (trusted) chained proxy at 178.62.234.129:443 to tcp://message.tieba.baidu.com:80: Unable to dial server (trusted) chained proxy at 178.62.234.129:443: dial tcp 178.62.234.129:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 2...continuing
Sep 11 05:46:37.683 - 1m17s ERROR balancer: balancer.go:100 Unable to dial via (trusted) chained proxy at 128.199.61.178:443 to tcp://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 128.199.61.178:443: dial tcp 128.199.61.178:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 1...continuing
Sep 11 05:46:41.240 - 1m21s ERROR balancer: balancer.go:100 Unable to dial via (trusted) chained proxy at 188.166.31.196:443 to tcp://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 188.166.31.196:443: dial tcp 188.166.31.196:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 11 05:46:51.591 - 1m31s ERROR balancer: balancer.go:100 Unable to dial via (trusted) chained proxy at 178.62.203.96:443 to tcp://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 178.62.203.96:443: dial tcp 178.62.203.96:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because con

**Comment by MrBoog** [comment]
Yep，can't google now

**Comment by Pixeladed** [comment]
ur a sick cunt arent ya?

**Comment by myleshorton** [comment]
Should be all set now with 2.0.6 @MrBoog @Pixeladed @fulljump @cmdlet1 and @lixiaodongsql 

We realize there's still on significant issue (#3147), and we're working on it! Thanks for you patience.
