### ISSUE TITLE
Hello, currently Lantern 2.0.5 can't work in China.

### ISSUE THREAD

**Issue by lixiaodongsql** [getlantern/lantern#3137]
Hello, currently Lantern 2.0.5 can't work in China. A moment ago I couldn't access Facebook and Google Group through Lantern proxy.  I uploaded my Lantern log file to Google Group Lantern Developer. 

https://groups.google.com/forum/#!topic/lantern-devel/Jz0huhk8-LE

Could you please help me solve this problem? Thank you very much for your help. I really appreciate it.

**Comment by h82258652** [comment]
Not work +1.
Could not access twitter. :(

**Comment by fulljump** [comment]
dorp this

**Comment by woodenwatcher** [comment]
I also have the same problem.The log info as follow:

Sep 15 03:41:39.680 - 0m21s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://config.getiantem.org:80: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:41:39.708 - 0m21s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://geo.getiantem.org:80: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:41:40.318 - 0m21s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://update.getlantern.org:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:41:55.413 - 0m36s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:42:00.718 - 0m42s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://geo.getiantem.org:80: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 1...continuing
Sep 15 03:42:01.410 - 0m42s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://update.getlantern.org:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 1...continuing
Sep 15 03:42:01.800 - 0m43s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://geo.getiantem.org:80: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:42:07.303 - 0m48s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://platform.twitter.com:80: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:42:07.433 - 0m48s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://www.google-analytics.com:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:42:10.319 - 0m51s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:42:10.339 - 0m51s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://en.wikipedia.org:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:42:12.483 - 0m54s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://www.facebook.com:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Sep 15 03:42:14.945 - 0m56s ERROR flashlight.analytics: analytics.go:82 Could not send HTTP request to GA: Post https://ssl.google-analytics.com/collect: net/http: TLS handshake timeout
Sep 15 03:42:16.408 - 0m57s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 1...continuing
Sep 15 03:42:22.413 - 1m3s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 188.166.106.179:443 to tcp://update.getlantern.org:443: Unable to dial server (trusted) chained proxy at 188.166.106.179:443: dial tcp 188.166.106.179:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 2...continuing
Sep 15 03:42:22.413 - 1m3s ERROR detour: detour.go:142 Dial detoured failed: Still unable to dial tcp://update.getlantern.org:443 after 3 attempts

**Comment by myleshorton** [comment]
Should work now in Lantern 2.0.6 (linked from getlantern.org and from main github page) @lixiaodongsql @h82258652 @fulljump @woodenwatcher

**Comment by h82258652** [comment]
@myleshorton 
Best thanks for the work.
2.0.6 works now.

**Comment by myleshorton** [comment]
Awesome @h82258652! Thanks for the report. We are still working on this one issue for http (versus https) sites and should have a fix soon #3147

**Comment by dozer47528** [comment]
it works ! thx

**Comment by myleshorton** [comment]
Awesome!

On Tue, Sep 15, 2015 at 6:59 PM, Dozer <notifications@github.com> wrote:

> it works ! thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3137#issuecomment-140598396>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by Centaur** [comment]
Here 2.0.6 is still not as stable as 2.0.2. Particularly `google.com` cannot be connected and lantern crashes eventually.  Roll back to 2.0.2 at last.

**Comment by myleshorton** [comment]
Hey @Centaur can you possibly send your logs to myles@getlantern.org? They're in C:\Users\YOUR_USERNAME\AppData\Roaming\Lantern\logs on Windows and in /Users/YOUR_USERNAME/Library/Lantern/Logs on OSX.
