### ISSUE TITLE
Chained server in go

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3186]
A replacement of ATS. Subtasks listed below:

- [x] Expand current `chained/server.go` to support nontunneled proxy requests

- [x] add options to run Lantern in chained server mode

- [x] support auth plugin

- [ ] mimic Apache when auth failed

- [ ] performance tuning

- [ ] standard conformity

**Comment by myleshorton** [comment]
We should probably use something like https://nmap.org/ to see what nmap thinks our server is too -- good way to verify that its output matches something we want it to match.

**Comment by uaalto** [comment]
hey @myleshorton and @fffw I marked the tasks I've done. Regarding the others:

- I didn't mark Apache mimicking because I don't know all the details of this, but I'm responding 404 for any request that looks like isn't coming from a Lantern client.
- I haven't done performance tuning, but I've taken it into account. Primarily the user db part might require some optimization, but I've been playing with an LRU cache in order to avoid hitting the DB, assuming that only a subset of users is going to be connected to the server at a given time.
- I didn't tackle the standards conformity issue much, but I've learnt from the Oxy forwarded which headers are expected. We should dive into this deeper I think.

I'm adding issues related to chained-server in its repository. The work remaining in the chained server is primarily fine-tuning it and make it stable for production (stress test, etc). The conversation yesterday with ATS reminded me of some stuff that needs to be done (wrap with the idle connections package and other stuff).

**Comment by uaalto** [comment]
Actually, regarding standards conformity, I've had the doubt if we should add Proto and Host headers along the X-Forwarded-For.

**Comment by myleshorton** [comment]
Yeah we should just be a transparent proxy on the upstream side as much as possible -- i.e. we probably should not look like a proxy at all. 

The *response* headers are generally much more important, but upstream matters to some extent too.

**Comment by fffw** [comment]
https://github.com/getlantern/http-proxy went online
