### ISSUE TITLE
lantern 2.0.8 bug report: no yaml, no run! 

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3214]
Recent lantern 2.0.8 cannot auto-generate yaml, hence when run lantern 2.0.8, no any response.
You must manually add yaml file and rename to lantern-2.0.8.yaml, then lantern can work, otherwise it won't work and even no tray to display
Pls fix this bug ASAP.

**Comment by edwardaa** [comment]
I have same issue, to solve that I reinstalled the lantern-installer-beta-64-bit.deb and it works

**Comment by carlos-wong** [comment]
me too, already reinstalled

**Comment by myleshorton** [comment]
Did you get 2.0.8 via auto-update? If so, does it work if you manually
download it instead from
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.exe
?

**Comment by edwardaa** [comment]
Yes, this issue occurs after auto update; it woks again after I downloaded the 2.0.8 .deb package and installed manually on Ubuntu 14.04.

**Comment by myleshorton** [comment]
Awesome @edwardaa thanks for the report! We're working on a fix now.

**Comment by myleshorton** [comment]
@yuan78, @carlos-wong, @edwardaa this issue should now be fixed in 2.0.9 (i.e. if you hadn't auto-updated to 2.0.8, auto-updating to 2.0.9 will result in a working version).

Thanks for bringing this to our attention, and apologies for the inconvenience. Please let us know if you have any more issues with Lantern. We'll also be providing Lantern Pro sometime fairly soon with additional features, and please don't hesitate to ask for a free year or something - we'd be happy to give that to you for your help.
