### ISSUE TITLE
致：开发者

### ISSUE THREAD

**Issue by yuliangyang** [getlantern/lantern#3241]
致开发者：
这几天看了蓝灯社区近几个月的动态
蓝灯一直半死不活
个人推测主要原因是蓝灯默认开启ie代理，被某数字软件上报数据，导致ip被封。
要想蓝灯长远，开发商必须彻底关闭IE代理。
国外的开发商太不理解国内行情
细数国内的开发代理软件，有哪个是默认开IE代理的
说实话，蓝灯默认开ie代理，能存活这么长时间，我都佩服
美国政府的资助不是盖的。。。
但是开发商关闭IE代理，不仅对蓝灯本身有好处
对蓝灯用户也有好处
还有他那种yaml自带规则的做法，实在不可行
应该另建一个pac文本，指定规则
现在科学上网谁没有代理扩展程序
又有几个去开IE
还有proxifier等等。。。。。。﻿

**Comment by yuliangyang** [comment]
hope you can turn off the IE proxy for default

**Comment by dac6acc4f** [comment]
Whatever, @yuliangyang , the ip set for IE proxy is a local one (e.g 127.0.0.1:8787), which will not be blocked.

**Comment by Arthur2e5** [comment]
>To Developers:
I looked at the news of the lantern community for these months
and it appears constantly half-dead
I think it's caused by lantern enables IE proxy by default, got reported by a *numeric software* (360), and got its IPs blocked

The issue reporter was actually saying that configuring a proxy by default makes lantern more attractive to Chinese antivirus or whatever computer security software like 360.cn, which are said to be collecting data on proxies for the authority, and such report may make lantern's new changes more easily known and defeated by that wall.

>To make lantern last long you should disable IE stuffs completely
You foreign devels are not familiar with our domestic proxy market
Look at all those proxies developed by domestic people, is there any that enables IE proxy by default? (have you ever used shadowsocks-csharp?)
To be frank I am so amazed at the truths that you can be alive for so long (READ THE DOCS!!!)
Financial help from US gov looks really powerful (huh??)

citation needed.

>But disabling the IE proxy thing is not only good for the proxy itself
it is also good for the users

Heh.

>and your method of self-including yaml lists is not quite applicable \[to users' real needs\]
you should let them define a PAC text separately and define rules

Huh. Lantern uses PACs to define the settings for IE. Go read the settings.

> these days nobody doesn't use proxy extensions
and few used IE

The IE proxy settings is not only for IE. It's in the system **Internet Options**. Many apps use it, including Chrome. You can also write conditionals in Proxy SwitchyOmega to conditionally follow IE proxy settings.

By the way are you ever aware that lantern is cross-platform and not sticked to system-specific things?

> and people also used proxifier [something like proxychains] and so on

It's trivial to pipe lantern thru proxifier. For the other way, explore the PAC.

* * *

Although it's almost [common sense](http://www.catb.org/esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s09.html) that security by obscurity in modern systems is a bad idea, some still believe this makes the gov think the given tool will be less popular so their ignorant people (*proles*) are less likely to be controlled by “an extremely small number of people with ulterior purposes” to cause trouble for them. Please note that many of these people also believed that censorship:

* protects foreign people, especially those so-called anti-china forces, from drowning inside a sea of angry Chinese people with justice
* acts as an IQ filter so only *the chosen* (or whatever, cleverer ones) who can “tell the truth from false reports”, and people with basic IQ could bypass the wall easily (this is wrong even under their logic, but well they might be too shorted-sighted or too self-conscious to see scholars studying non-IT things being unable to use Google Scholar).
  * I have seen programmers selling VPNs talking with such logic when I pointed out that his IPSec was vulnerable to replay attacks by the GFW and at least some obfuscator wrapper like obfs4 should be used. 2 weeks later his own super-industrial, never-used-by-proles IPSec tunnel got screwed by GFW. Good game.

Anyway, such idea is contradictory with the *open Internet for everyone* slogan and should not be considered seriously in lantern development. Obscurity may decrease the priority of banning a specific tool, but for super jumbo method packs like lantern…

* * *

And don't forget that not only China censor the internet.

**Comment by aranhoide** [comment]
Thanks to all participants, and sorry to have let this ticket unaddressed for so long.  We have diagnosed and fixed the issues that Lantern was having prior to this ticket being logged.  Lantern has been growing steadily and without interruption since.  We have found no causality between the fact that Lantern sets itself as system proxy and these issues.

We often have specific tickets dealing with problems with antivirus software.  We'll keep the information on this report in mind, thanks.

We don't think hiding from antivirus software is a viable long term strategy for an app that aims to be widely used.  And we aim to get wide enough usage that censors could ask national antivirus companies to target Lantern specifically, whether it sets itself as system proxy or not.
