### ISSUE TITLE
Lantern not working with Edge browser

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3299]

**Comment by cuanyu** [comment]
I have two PCs. One is running Windows 10 professional. Edge could not work with Lantern but Chrome could on the same machine. Another one is Windows 10 insider preview build 10547. Both Edge and Chrome could work fine with Lantern.

I have checked the proxy setting on both machine and they are same. 

I am not if it is because of antivirus but both machine are using Windows defender. I don't how to check if this 16823 port is blocked or not.

**Comment by cuanyu** [comment]
What's more, on the same machine IE works fine with Lantern too. I don't have other browsers on the machine. So I guess it is just the Edge which has problem working with Lantern.

**Comment by fffw** [comment]
No longer true.
