### ISSUE TITLE
Lantern doesn't work anymore.

### ISSUE THREAD

**Issue by kooboo-jianghao** [getlantern/lantern#3309]
Got this error for all sites:
Unable to get a connection: Still unable to dial tcp://doesnotexist.com:80 after 3 attempts

**Comment by liugangnhm** [comment]
same to me.

**Comment by myleshorton** [comment]
Thanks @kooboo-jianghao and @liugangnhm! Can you possibly send your logs to me at myles@getlantern.org?

Instructions are here:
https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by woodenwatcher** [comment]
Today,my lantern also can not work.The error info as follow:

Nov 17 01:08:00.064 - 39947m54s DEBUG balancer: balancer.go:98 Dialing tcp://doesnotexist.com:80 with (trusted) chained proxy at 45.32.253.119:443
Nov 17 01:08:00.286 - 39947m54s DEBUG geolookup: geolookup.go:133 Fetching ip...
Nov 17 01:08:00.286 - 39947m54s DEBUG flashlight.util: http.go:89 Using dual fronter
Nov 17 01:08:00.286 - 39947m54s DEBUG flashlight.util: http.go:124 Sending request via DDF
Nov 17 01:08:00.286 - 39947m54s DEBUG flashlight.util: http.go:208 Creating new HTTPClient with proxy: 127.0.0.1:8787
Nov 17 01:08:00.286 - 39947m54s DEBUG flashlight.util: http.go:238 Waiting for loopback proxy server to came online...
Nov 17 01:08:00.287 - 39947m54s DEBUG flashlight.util: http.go:252 Connected to proxy on localhost
Nov 17 01:08:00.287 - 39947m54s DEBUG flashlight.util: http.go:137 Sending chained request
Nov 17 01:08:00.287 - 39947m54s DEBUG fronted: direct.go:145 Dialing to &{oceanpark.com.hk 54.230.5.61}
Nov 17 01:08:00.288 - 39947m54s DEBUG balancer: balancer.go:98 Dialing tcp://doesnotexist.com:80 with (trusted) chained proxy at 45.32.253.119:443
Nov 17 01:08:00.932 - 39947m55s DEBUG fronted: direct.go:151 Could not dial to 54.230.5.61, Unable to dial masquerade oceanpark.com.hk: x509: certificate is valid for *.telestream.net, telestream.net, not oceanpark.com.hk
Nov 17 01:08:00.932 - 39947m55s DEBUG fronted: direct.go:138 Continuing on certificate error
Nov 17 01:08:00.932 - 39947m55s DEBUG fronted: direct.go:145 Dialing to &{playmmc.com 204.246.169.111}
Nov 17 01:08:01.739 - 39947m55s DEBUG fronted: direct.go:159 Got successful connection to: &{playmmc.com 204.246.169.111}
Nov 17 01:08:01.739 - 39947m55s DEBUG fronted: direct.go:168 Wrapping connecting in idletiming connection
Nov 17 01:08:01.739 - 39947m55s DEBUG fronted: direct.go:170 Returning connection
Nov 17 01:08:02.471 - 39947m56s DEBUG flashlight.util: http.go:106 Got successful HTTP call!
Nov 17 01:08:02.471 - 39947m56s DEBUG flashlight.util: http.go:130 Fronted request succeeded
Nov 17 01:08:02.471 - 39947m56s DEBUG flashlight.util: http.go:157 Got good response
Nov 17 01:08:02.471 - 39947m56s DEBUG geolookup: geolookup.go:161 Successfully looked up IP '114.255.31.133' and country 'CN'
Nov 17 01:08:07.441 - 39948m1s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to connect://clients4.google.com:443: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Nov 17 01:08:07.441 - 39948m1s DEBUG flashlight.logging: logging.go:218 Not logging duplicate: ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to connect://clients4.google.com:443: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing

Nov 17 01:08:07.441 - 39948m1s DEBUG balancer: balancer.go:98 Dialing connect://clients4.google.com:443 with (trusted) chained proxy at 45.32.253.119:443
Nov 17 01:08:12.974 - 39948m7s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to connect://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 2...continuing
Nov 17 01:08:12.974 - 39948m7s DEBUG flashlight.logging: logging.go:218 Not logging duplicate: ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to connect://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 2...continuing

Nov 17 01:08:12.974 - 39948m7s ERROR detour: detour.go:142 Dial detoured failed: Still unable to dial connect://logs-01.loggly.com:443 after 3 attempts
Nov 17 01:08:12.974 - 39948m7s DEBUG flashlight.logging: logging.go:218 Not logging duplicate: ERROR detour: detour.go:142 Dial detoured failed: Still unable to dial connect://logs-01.loggly.com:443 after 3 attempts

Nov 17 01:08:12.974 - 39948m7s DEBUG flashlight.client: handler.go:101 Could not dial Still unable to dial connect://logs-01.loggly.com:443 after 3 attempts
Nov 17 01:08:12.974 - 39948m7s DEBUG flashlight.client: handler.go:153 Responding 502 to //logs-01.loggly.com:443
Nov 17 01:08:14.577 - 39948m8s DEBUG balancer: dialer.go:147 Error testing dialer (trusted) chained proxy at 45.32.253.119:443 to humans.txt: Get http://www.google.com/humans.txt: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Nov 17 01:08:21.065 - 39948m15s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to tcp://doesnotexist.com:80: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 2...continuing
Nov 17 01:08:21.065 - 39948m15s DEBUG flashlight.logging: logging.go:218 Not logging duplicate: ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to tcp://doesnotexist.com:80: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 2...continuing

Nov 17 01:08:21.065 - 39948m15s DEBUG flashlight.client: reverseproxy.go:50 Could not get balanced dialer Still unable to dial tcp://doesnotexist.com:80 after 3 attempts
Nov 17 01:08:21.065 - 39948m15s DEBUG flashlight.client: handler.go:36 Could not get a reverse proxy connection -- responding bad gateway
Nov 17 01:08:21.065 - 39948m15s DEBUG flashlight.client: handler.go:165 Responding BadGateway: Unable to get a connection: Still unable to dial tcp://doesnotexist.com:80 after 3 attempts
Nov 17 01:08:21.065 - 39948m15s ERROR flashlight.util: http.go:144 Chained request failed Bad response code: 502
Nov 17 01:08:21.065 - 39948m15s DEBUG flashlight.logging: logging.go:218 Not logging duplicate: ERROR flashlight.util: http.go:144 Chained request failed Bad response code: 502

Nov 17 01:08:21.285 - 39948m15s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to tcp://doesnotexist.com:80: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing
Nov 17 01:08:21.285 - 39948m15s DEBUG flashlight.logging: logging.go:218 Not logging duplicate: ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to tcp://doesnotexist.com:80: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing

Nov 17 01:08:21.285 - 39948m15s DEBUG balancer: balancer.go:98 Dialing tcp://doesnotexist.com:80 with (trusted) chained proxy at 45.32.253.119:443
Nov 17 01:08:28.450 - 39948m22s ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 45.32.253.119:443 to connect://clients4.google.com:443: Unable to dial server (trusted) chained proxy at 45.32.253.119:443: dial tcp 45.32.253.119:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 1...continuing

**Comment by myleshorton** [comment]
Thanks @woodenwatcher and everyone else. What operating system is everyone on? Also, does Lantern work if you restart it?

**Comment by kooboo-jianghao** [comment]
I use Windows 10, and it's no use to restart.

Sent from Outlook




On Tue, Nov 17, 2015 at 1:25 PM -0800, "myleshorton" <notifications@github.com> wrote:





Thanks @woodenwatcher and everyone else. What operating system is everyone on? Also, does Lantern work if you restart it?

---

**Comment by aranhoide** [comment]
BTW, please send logs to team@getlantern.org and don't paste them in github issues.  The latter exposes sensitive information (for example, your IP and that of proxies).

@woodenwatcher : the proxy that is assigned to you seems to be working well.  Does it always fail for you or only at certain times of the day?  What Lantern version are you running?

**Comment by woodenwatcher** [comment]
I use Windows7, and it's no use to restart and reinstall
