### ISSUE TITLE
Bugs setting the system proxy for all apps on Windows 10

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3359]
See the discussion at https://groups.google.com/forum/#!topic/lantern-devel/j7yBGx4xEDc

**Comment by myleshorton** [comment]
@fffw do you have Windows 10 handy?

**Comment by fffw** [comment]
I downloaded Windows 10 months ago but could not run it in VM. Maybe try again later.

**Comment by pjzhong** [comment]
I am in  a censor region there is no google..........

**Comment by cloudhan** [comment]
This is not a bug, it is the default setting for Windows 8 and above to isolate `Windows Runtime apps` from loopback connection

Windows App does not allow loopback connection since Windows 8, you should add exemption for the specific app to allow it connect to localhost
check this [link](https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx)

you can also use this utility on Win10
[Windows 8 Loopback Exemption Manager](https://loopback.codeplex.com/)

**Comment by fffw** [comment]
Wow @cloudhan this is really useful! We definitely need a way to overcome it.

**Comment by myleshorton** [comment]
Thanks @cloudhan. This should be fixed in 2.1.0
