### ISSUE TITLE
Upgrade to Go 1.5.3 to fix RSA-related Bug

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3412]
https://groups.google.com/forum/#!topic/golang-announce/MEATuOi_ei4

**Comment by aranhoide** [comment]
The phrasing in that report suggests that only servers are affected.  We [have already upgraded](https://github.com/getlantern/lantern_aws/commit/b8139b49bee57620f53cc1b41c4d89f5f018345d) our servers to this go version because of this issue.

I suppose if we're upgrading to 1.5 for the next client release we might as well make sure we use 1.5.3 or later.  Anyway, do you believe this could be affecting Lantern clients too?

**Comment by oxtoacart** [comment]
Ah, cool, I didn't realize that our servers are already on 1.5.3.  Yes, this does appear to be server-specific.  Thanks!
