### ISSUE TITLE
Improve blocking detection

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3438]

**Comment by uaalto** [comment]
Some interesting tools for the task:
https://ooni.torproject.org/
http://www.measurementlab.net/tools/ndt
http://n1.netalyzr.icsi.berkeley.edu/analysis/
https://zmap.io/

**Comment by aranhoide** [comment]
This is not a short term proposal, since it would involve client changes.

When thinking of using the Lantern client to gain insight about blocking, the main problem is that users with blocked proxies may be unable to report back to us in any way (i.e., if DDF is not working).  But unless we're totally down in a censored region, there are other clients there that can reach us.

So we could put up a server and make clients ping it periodically for requests to try some proxy and report on its reachability/performance/etc.

For safety (i.e., so we don't leak proxy IPs too much) the server would only order such tasks to a small sample of users.  We could pick clients assigned to proxies that have stayed unblocked for long, etc.

Clients that can't reach their proxy but can DDF can also report this condition to this server.  This server could also detect when too many users assigned to a given proxy stop pinging altogether.

**Comment by myleshorton** [comment]
It seems like in practice recent changes along with pretty darn robust existing systems have made this largely a non-issue. Closing until we again start seeing blocked servers we don't successfully detect.
