### ISSUE TITLE
When sharing in facebook for the mobile Ad, it posts only the link and not the message

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3481]
![fb sharing](https://cloud.githubusercontent.com/assets/11394369/12797549/6d651da8-ca79-11e5-9b0b-e5e7572c79e0.png)

**Comment by myleshorton** [comment]
Can you look at this @xiam?

**Comment by xiam** [comment]
It seems that setting custom text is no longer possible with the `sharer.php` link provided by facebook: @myleshorton, @sunshine19090 

https://developers.facebook.com/docs/apps/review/prefill

> Pre-fill the user message parameter with any content the user didn't enter themselves, even if they can edit or delete that content before sharing. This applies to posts, comments, photo captions, and photo album captions.

Besides that, they actually removed the parameter that can be used to share predefined text.

It looks like if we create a Facebook app and ask the user to log in and give us write permissions we will be able to prefill this text:

https://developers.facebook.com/docs/javascript/examples#dialogs

Facebook also looks for certain meta tags on the URL that we're trying to share (that's why our other share link looks pretty and has an Lantern icon, but this one is linked from S3).

**Comment by myleshorton** [comment]
OK let's just not worry about this for now then @xiam!
