### ISSUE TITLE
Experiment with thousandeyes

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3611]
@fffw I thought this would be good for you to look at. It basically gives us better visibility into connectivity to our data centers. The trial doesn't have points-of-presence in China, but the enterprise does. @uaalto you would be interested in this too I think.

**Comment by myleshorton** [comment]
In TMS guys...

**Comment by uaalto** [comment]
Thanks @myleshorton! It seems super interesting.

**Comment by myleshorton** [comment]
This is pretty interesting too @uaalto and @fffw:

https://blog.thousandeyes.com/internet-censorship-around-the-world/

**Comment by uaalto** [comment]
I love it!!

**Comment by uaalto** [comment]
I've read the document and it does provide useful visualization of 3 most typical censorship techniques. It is particularly useful to understand how to use Thousand Eyes to help diagnose these visually.

**Comment by uaalto** [comment]
So, I've been playing with thousandeyes and find it useful for identifying network conditions. There would be two use cases I can think node-to-cloud, and cloud-to-cloud. The former is already set up by @fffw from China. However, setting up one from Iran might not be a good idea because it produces a lot of traffic (moves files of 10/100Mb).
Cloud-to-cloud is useful to see potential issues in the paths between our different providers. In my opinion, most if not all can be done manually, ThousandEyes provides convenience and visualization. In our current plan the tests are: ping, TCP connectivity, bandwidth and TCP/ICMP route visualization. Also a bunch of DNS tests, but these might be less useful for internal troubleshooting unless we want to identify DNS poisoning at some point.
