### ISSUE TITLE
ui.lantern.io cannot be reached

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#3671]
This one was reported by @Rice321 and @Derekf5 on current 2.1.0 QA.

Looks like the browser is trying to do DNS resolution instead of letting Lantern handle it.

**Comment by oxtoacart** [comment]
The main reasons I can think of for this happening is that the user has a proxy switcher that's bypassing Lantern or the user is using some other extension that's actually doing DNS resolution on behalf of Chrome and not respecting proxy settings.  The 2nd explanation could also explain why we see a lot of requests on our servers for IP addresses instead of DNS names.

**Comment by xiam** [comment]
@oxtoacart I'm gonna try to replicate this by using an extension. Do you think it would be useful to point the real ui.lantern.io to 127.0.0.1 and go back to the unprivileged port we were using? The bad part about doing that is that DNS is easily filtered/spoofed.

**Comment by xiam** [comment]
Possibly related: https://github.com/getlantern/lantern/issues/3651

**Comment by oxtoacart** [comment]
> The bad part about doing that is that DNS is easily filtered/spoofed.

True, but if folks are using unblocking extensions that protect DNS, that might not be so bad in this case.

**Comment by myleshorton** [comment]
So most of these extensions AFAIK aren't just DNS but are setting the HTTP
proxy - certainly hola and all the proxy switchers.

**Comment by myleshorton** [comment]
This is one of the biggest issues users have, however, so it would probably
be good just to solve it given that 2.1.0 isn't super urgent. For example
for Derek and Rice Lantern wouldn't have actually worked for them anyway
even if the UI had loaded in the previous version.
