### ISSUE TITLE
Throttle bandwidth for users that have reached their bandwidth cap

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3716]
This will be useful potentially for pro but also for general info and blocking resistance. I think you started this @uaalto

**Comment by uaalto** [comment]
This is pretty much done IRCC, @myleshorton. It's based on @fffw's measured, and the code is lying inactive but ready to be turned on.
Probably the most important decision here would be which Redis DB to use, if to set up one for analytics purposes or the same on we use for config-server. I'm more inclined to separating concerns, but is also one more thing to manage.

**Comment by myleshorton** [comment]
Awesome @uaalto! This one's not urgent at this point, but I think it will be particularly useful for blocking resistance.

**Comment by myleshorton** [comment]
As we discussed on our call with @oxtoacart, @aranhoide, and @uaalto, the simplest initial approach might just be to use device IDs.

**Comment by uaalto** [comment]
This is already implemented. It is set up to report to Redis (as mentioned, currently deactivated). This will produce a ton of keys, however. I'm going to drastically reduce the number of keys by using a different key scheme, and we should be good to go.

**Comment by myleshorton** [comment]
Adding this one to the backlog @uaalto.

**Comment by uaalto** [comment]
Great @myleshorton !
We should also add/create the TLS Redis related ones, because we need to send the data over a secure channel.
This would need reworking now that the config-server has moved to DO, and needs implementation on http-proxy-lantern:
- https://github.com/getlantern/http-proxy-lantern/issues/60
- https://github.com/getlantern/config-server/issues/41

This is the now outdated PR: https://github.com/getlantern/config-server/pull/43

**Comment by oxtoacart** [comment]
The main thing that's left is hardening the Redis connections, including adding TLS support and reliable delivery.

**Comment by uaalto** [comment]
Besides Redis hardening, these other tasks remain:

- [ ] Once the limit is reached, trigger bitrate control. We need to feedback the current value to http-proxy, because it's currently working only with atomic increments.
- [ ] Bitrate control. I've found a couple solutions for this, and implementation seems simple at first.
- [ ] Time-based restart of bandwidth usage. Key expiration could be the simplest solution. Would need to add a test of key preexistence in http-proxy per flight though, so other solutions are worth exploring.

**Comment by uaalto** [comment]
PR in https://github.com/getlantern/http-proxy-lantern/pull/80

**Comment by sunshine19090** [comment]
@myleshorton While throttling, I see even the unblocked and unproxied sites are slow. Shouldn't we throttle only the blocked sites or only the sites that we proxy?

**Comment by myleshorton** [comment]
Yeah. The throttling is on the server side, though @sunshine19090, so it's unlikely we'd inadvertently slow down sites locally somehow.

**Comment by oxtoacart** [comment]
@sunshine19090 Is the Proxy All option on?

**Comment by sunshine19090** [comment]
Sorry @oxtoacart, I don't remember but there is a chance that I might have used that option. I will try it once more with the new build without the proxy all option on.
