### ISSUE TITLE
can't visit developer.android.com in China

### ISSUE THREAD

**Issue by Kutear** [getlantern/lantern#3717]
other site like google and facebook is OK

**Comment by fffw** [comment]
@Kutear Can you describe the details? What error you got? Which version of OS/Browser/Lantern you are using?

**Comment by Kutear** [comment]
@fffw Lantern 2.0.16  chrome browser for win7 

![qq 20160304152727](https://cloud.githubusercontent.com/assets/8605389/13520725/c5dba644-e21d-11e5-9c80-3b59167494ef.png)

**Comment by fffw** [comment]
So Chrome didn't hit Lantern server at all. Describing more details, what you've tried and the result will help us to isolate

**Comment by DoHello** [comment]
sorry, i do not deal your problem now. i try do it now.



719285662@qq.com
 
From: KuTear
Date: 2016-03-04 15:30
To: getlantern/lantern
Subject: Re: [lantern] can't visit developer.android.com in China (#3717)
@fffw Lantern 2.0.16 chrome browser for win7

**Comment by Kutear** [comment]
@fffw i don't have proxy switcher extension,The problem is other blocked site is ok,only developer.android.com can't visit

**Comment by DoHello** [comment]
Developer.android.com can visit now, but is very slow


719285662@qq.com
 
From: KuTear
Date: 2016-03-04 16:52
To: getlantern/lantern
CC: DoHello
Subject: Re: [lantern] can't visit developer.android.com in China (#3717)
@fffw i don't have proxy switcher extension,The problem is other blocked site is ok,only developer.android.com can't visit
