### ISSUE TITLE
Lantern works weirdly on Win 10 Edge  

### ISSUE THREAD

**Issue by Rice321** [getlantern/lantern#3784]
It happens to some users: Lantern works well on other browsers except Edge on Win 10. The user opens Lantern, then Edge doesn't work at all, unless he opens any pages on other browsers first then Edge can work. Especially, if the user opens an unblocked page on other browser, then he can use Edge for unblocked websites; if the user opens a blocked page on other browser, then Edge can work for blocked websites as well. This sounds very odd. 

Here is a quote from the user:
“在其他浏览器都非常流畅，唯独在win10的edge浏览器上不好用，情况是，每次开启lantern后，用edge都无法上网，只有在用其他浏览器登陆一次网页后才能用edge浏览网页，而且是其他浏览器浏览过墙内的网站后，edge能上墙内网，其他浏览器登录过墙外网站后，edge才能浏览墙外的网站。出现这种情况的不只我一个，大多数用win10的都遇到这种情况，至少我推荐给周围人用，都是这样”

**Comment by aranhoide** [comment]
This seems really bad, but assigning P2 since there's at least a known workaround and users can use other browsers, and similar bugs with Chrome get this priority.  @Rice321 feel free to bump to a higher priority if you think I'm underestimating the importance of this.

IIRC @myleshorton was looking into this, so I'm assigning to him.

**Comment by xiam** [comment]
Hey @Rice321, I think we're gonna smash this bug on the next release.

**Comment by xiam** [comment]
Ready for testing too, @sunshine19090

**Comment by myleshorton** [comment]
Thanks @xiam! Can you just move tickets that are done to the "done" column too? Thanks!

**Comment by Rice321** [comment]
Thank you @aranhoide and @xiam !
