### ISSUE TITLE
Request: Lantern for DDWRT

### ISSUE THREAD

**Issue by matthewbassett** [getlantern/lantern#3909]
Hi,

I have been going over lantern, and I am very impressed, nice work. Simple idea and beautiful execution. Would it be feasible to run Lantern on something like DDWRT to give uncensored internet access to all devices on a wireless network? This is an awesome project, and as someone living in China I can also say VERY much appreciated.

**Comment by myleshorton** [comment]
Thanks Matthew! That should be possible for sure. I've never personally
played with DDWRT but check out the section of the README entitled "*Building
Lantern for running on a server**"*. Does that do the trick or is DDWRT not
typically x86?

Hi,

I have been going over lantern, and I am very impressed, nice work. Simple
idea and beautiful execution. Would it be feasible to run Lantern on
something like DDWRT to give uncensored internet access to all devices on a
wireless network? This is an awesome project, and as someone living in
China I can also say VERY much appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/getlantern/lantern/issues/3909>

**Comment by macrowh** [comment]
yes. too many lantern user in china request the  installer package. ddwrt is a router OS. And the  cpu  is arm  or  mips.  So  would  lantern  develop  team release an arm  linux binary installer. thanks！

**Comment by matthewbassett** [comment]
Good deal! (: Thanks for a great product, and I look forward to the
possibility of an ARM based installation (:

Matt

On Sat, Apr 16, 2016 at 9:28 AM macrowh <notifications@github.com> wrote:

> yes. too many lantern user in china request the installer package. ddwrt
> is a router OS. And the cpu is arm or mips. So would lantern develop team
> release an arm linux binary installer. thanks！
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3909#issuecomment-210704830>
>
-- 
Thanks,

Matt

**Comment by aranhoide** [comment]
Thanks for your feedback and suggestion, @matthewbassett !

I'll refer to this issue from https://github.com/getlantern/lantern/issues/3054 and mark this as a duplicate to keep this discussion but centralize any future talk in the other one.
