### ISSUE TITLE
Language in Lantern page is not translated in IE when selecting zh-cn

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4038]
![image](https://cloud.githubusercontent.com/assets/11394369/14692278/ed7b3d6a-070a-11e6-8131-bb603b6d15a2.png)

**Comment by fffw** [comment]
That's because the translation library Lantern desktop uses, `angular-translate`, determines language in following order:
```
navigator.languages[0]
navigator.language
navigator.browserLanguage
navigator.systemLanguage
navigator.userLanguage
```
Chrome/Firefox set 1-2, Safari set 2, IE set 2-5, but only 5 is changed to zh-CN when the languages in "Internet Options" is changed, so language is detected as en_US. In a system with Chinese version of IE installed, it should detect correctly.

**Comment by myleshorton** [comment]
OK so I'm closing then @fffw. I assume this works on your machine?

**Comment by fffw** [comment]
Actually I don't have a machine or VM with Chinese version of Windows. Will try get one. `angular-translate` has worked for a long time for Chinese user so I don't think it breaks in this version.
