### ISSUE TITLE
Add back weight to ClientConfig

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4080]
Without this, updating our genconfig code will create configs that break all clients prior to 2.1.2.

**Comment by myleshorton** [comment]
FYI @aranhoide **do not** update genconfig to the latest code please, as that will break a lot of stuff.

**Comment by oxtoacart** [comment]
Turns out this isn't an issue.  The only thing that genconfig generates that we need is the embedded configuration, which gets backed into the client executable.  The cloud-based configuration of fallbacks is done here:

https://github.com/getlantern/lantern/blob/master/src/github.com/getlantern/flashlight/genconfig/cloud.yaml.tmpl#L8

And the cloud-based configuration of user-specific servers is done here:

https://github.com/getlantern/lantern_aws/blob/master/lib/vps_util.py#L258

Both still include the weight, so we're good.
