### ISSUE TITLE
Support setting the feed by region as well as locale

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4163]
Unfortunately many users in different regions don't have their browsers set to the expected locale. Very few users in Iran have their systems set to fa_IR, for example, and most users in Malaysia also have en_US set as their locale.

We can use the country detection within Lantern to override the locale setting to get around this.

**Comment by atavism** [comment]
@myleshorton Another option, maybe in addition to detecting the user's country, would be to have a drop-down menu with every region we have a feed available in on the main screen (it could be really small, possibly in the upper corner). Maybe whichever country we detect the user in becomes the default selection?

**Comment by oxtoacart** [comment]
@myleshorton I like @atavism's suggestion of doing our best to default but providing a drop-down to choose.  This would be especially good for travelers and expats who are interested in their home news rather than the news for whatever country they happen to be in.  That said, just using Lantern's geolocation to start is probably a decent initial solution.

**Comment by fffw** [comment]
Our hypothesis on users' preference may not that accurate. If an Iranian uses en_US locale, what's the probability she wants local contents all in Persian, instead of global news in English? If as @atavism suggested we provide a dropdown somewhere, user can select whatever she wants and stick with it, geolocation seems unnecessary.

**Comment by myleshorton** [comment]
Yeah I think ultimately we should also provide a dropdown @fffw, @oxtoacart, @atavism. This is a blocker for 2.2.0, however, so I don't think we probably want to get into a dropdown now.

In both Iran and Malaysia the dominant language is not english. Why users' locales are so often english in both is actually a bit unclear, but just thinking about it in basic terms all of the content we're providing to Iran is in Persian and all of the content we're providing to Malaysia is in Malay. That's also the best, most relevant content we've identified from talking to Malaysians and Iranians, and no one ever suggested any english content. So I think serving the Malay feed in Malaysia and the Persian feed in Iran is pretty clearly what we want, but of course as @oxtoacart there are ultimately no blanket rules, so giving the user a dropdown as well would surely help.

**Comment by myleshorton** [comment]
Oh, also there's a pending PR for this already at #4167

**Comment by sunshine19090** [comment]
I tested by manually changing the language in the browser and the system. I couldn't test where Lantern detects the country and then providing the feed based on that.
