### ISSUE TITLE
Use detour/shortcut on mobile

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4182]

**Comment by atavism** [comment]
@myleshorton Gonna bump this to a ``P1`` since we've been hearing a lot from users experiencing slowness proxying everything w/ Lantern. Enabling detour and connecting directly whenever possible would go a long way towards counteracting that!

**Comment by p3rcya** [comment]
@Derekf5 We would need a proxy all and smart proxy option in the menu then. By default it should be smart proxy.

**Comment by oxtoacart** [comment]
Note - this applies only to China where we can use the DNS antidote technique.

**Comment by myleshorton** [comment]
It's unclear what the best approach is here between shortcut, detour, etc, and it's possible some refactoring might be required. The biggest issue I think is that mobile sends DNS requests separately.

**Comment by joesis** [comment]
Made Lantern Android working with `shortcut`, but DNS requests are sent over `udpgw`, instead of the local DNS server. It's possible to pass a local DNS server to go code for `shortcut`, but it feels unnecessary to me as foreign DNS server would resolve most domestic sites to domestic IP address too.

**Comment by oxtoacart** [comment]
@joesis Awesome! I'd be happy to review the PR if you want.

**Comment by joesis** [comment]
Thanks @oxtoacart! I'm still playing with a few errors showing up in the log. Maybe refactor a bit. Will ping you once it's ready.
