### ISSUE TITLE
Lantern loading thumbnails even though feed is hidden

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4221]

**Comment by oxtoacart** [comment]
The UI loads about 70 thumbnails right at start up.  But ...  This only happens if the feeds are hidden.  If you choose to view feeds and then reload the UI, it only loads 10 or so, and loads more as you scroll the all feed.  If you comment out the all feed, then no images are loaded.

So, what I think is happening is that the infinite scroll logic isn't working correctly when the feeds are suppressed.

**Comment by sunshine19090** [comment]
I don't see any difference in the UI view. Closing!
