### ISSUE TITLE
Mobile - Send push notification(s) when user is nearing bandwidth cap

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4391]

**Comment by atavism** [comment]
Hey @uaalto, I think this one should be assigned to you actually. Are you sending any push notifications whenever the user is nearing the bandwidth cap currently?

**Comment by uaalto** [comment]
No, we are not doing that @atavism. The reason is that we don't have any centralized process monitoring usage, the decision is made by the proxies based on usage and they cannot do the notification. 
I would actually avoid doing push notifications if the client can handle it, since it will receive the usage data anyway. The reason is that we would need to set up a background process in the Pro server or separate service to do it. What bothers me is to put that extra pressure on Redis, if we can avoid it. We cannot make this O(log n) with the current scheme, because we rely on key expiration (that is, we are not using ordered sets for this reason). That results in the need to do everything by scanning, so O(n), and those scans are somewhat expensive, especially with the space of free users.
So the question here is if we are able to handle this on the client itself to avoid setting up a process that scans Redis.

**Comment by myleshorton** [comment]
Closing in favor of https://github.com/getlantern/lantern-internal/issues/813
