### ISSUE TITLE
Purchase option page height a bit off

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4537]
The two year plan height is a little bit off
![image](https://cloud.githubusercontent.com/assets/7925929/15831720/c3465b86-2bd3-11e6-8b4f-7e6f8bc0e672.png)
For your reference, it should look like getlantern/lantern#4462 (comment)

**Comment by p3rcya** [comment]
@atavism on nexus 5

**Comment by atavism** [comment]
This actually hasn't been an issue for me:

![image](https://cloud.githubusercontent.com/assets/6346213/16271228/f90e2b50-384d-11e6-8234-e5f6123113ad.png)

So to debug it, I had to update to Android Studio 2 and use a Nexus 5 Android AVD emulator. That finally revealed an issue with a layout width having the wrong attribute, that only affects newer versions of Android. That caused the "Best Value" tag not to appear for you. This should be fixed in the next build that goes out.

**Comment by p3rcya** [comment]
@atavism Still present in 0623

**Comment by atavism** [comment]
Hey @p3rcya, I know this one is a bit old, but is it still an issue with you w/ 3.0.12? I tested w/ a LG Nexus 5 running 6.0.1, and it looks fine to me.

**Comment by p3rcya** [comment]
It's fixed 3.0.12
