### ISSUE TITLE
Create easily runnable end-to-end testing environment

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4609]

**Comment by myleshorton** [comment]
use top.sls with a new type of machine that includes everything? then something that somehow links them all? might run into issues with linux-specific configs like ufw?

**Comment by aranhoide** [comment]
I was proposing top.sls as a way to create a docker image, so the issue with ufw wouldn't be Linux dependencies but rather the fact that everything runs locally so firewall configurations don't make much sense.  Other things that will be perhaps impossible or impractical to test in a one-machine setting are CDN-populated headers to the config server, and anything involving domain fronting.

Maybe the easiest way to test stuff locally would be with a script that gets passed a root folder where we have checkouts of all relevant projects and builds them all and launches them in the right order with the right configs so they talk to each other.  This may require modifications to some projects so they can run in this way at all.

**Comment by myleshorton** [comment]
FYI @aranhoide, @xiam, @ox, @uaalto -- please feel free to add any additional notes. @xiam mentioned vagrant might make a lot of sense for this.

**Comment by myleshorton** [comment]
Good points @aranhoide. I wonder if we could domain front to ourselves with a little UPNP/NAT-PMP mapping!

**Comment by fffw** [comment]
I'm wondering if the memory limit can be easily exceeded by running all the services on single physical machine. Moreover, docker based deployment is different from how we deploy production servers, which may not capture certain configuration errors.

If we want to simulate production environment as much as possible, we can create separate accounts for Heroku and DO, launch VPSes and applications accordingly via script. That way we can possibly make the test faster by parallel some initialization, and take benefits of the fast and reliable internet access. It also gives us the ability to stress testing services by launching multiple load simulators, etc. We can even improve our DevOps ability because some of the scripts can be also used in production.

It will incur some additional costs, but I don't expect them to be high.

It comes to my mind when I recall the old story that a Thoughtworks project spawns tens of Amazon EC2 instances on demand to run acceptance and stress test.

@xiam @myleshorton how do you think?

**Comment by xiam** [comment]
I think that we should try running locally as first approach, using portable scripts for the setup. If memory is a problem we'll hit a hard wall, in that case we should be able to use a different machine with the same scripts.

**Comment by myleshorton** [comment]
Yeah TBH I think both approaches are totally valid, and that we can just continue to make progress on all fronts. We could also start deploying more things in production using docker in theory.

**Comment by myleshorton** [comment]
Actually, also JC I've just been playing with wercker a bit, and it seems like it might be an interesting piece of the puzzle for this -- like it seems like it could relatively easily spin up your docker background services and automatically run the tests possibly in addition to any local testing you enable. I was just looking at this:

http://devcenter.wercker.com/docs/wercker-yml/wercker-classic.html

**Comment by myleshorton** [comment]
Actually it seems like their "docker stack" might be a really slick fit @xiam:

http://devcenter.wercker.com/docs/pipelines/stacks.html

**Comment by xiam** [comment]
Here we have instructions on how to run a local cloud-master and proxies using vagrant: https://github.com/getlantern/lantern_aws/pull/348

**Comment by myleshorton** [comment]
Discussed on the call and @oxtoacart is helping review these changes.

**Comment by oxtoacart** [comment]
There might be a more efficient way to accomplish the same testing goal without docker, for example just a script that launches everything into a real staging environment. Let's carefully consider what we want to do going forward.

Perhaps also just a basic smoke test that installs the client into a Wercker environment and makes sure that we can start, proxy, etc.

**Comment by oxtoacart** [comment]
This ship has sailed.
