### ISSUE TITLE
Change default payment details to default to alipay for chinese users

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4611]
I don't know we're able to change it since it's handled on Stripe. But for Chinese users, it should default to Alipay rather than credit card.

**Comment by atavism** [comment]
Right now, whenever you select a Pro plan, you're re-directed to the checkout page with the option to choose Alipay. You're saying, for Chinese users (presumably detected by locale), we just open Alipay (in the browser) right away, right? Yeah, that should be a quick change.

**Comment by p3rcya** [comment]
Current screen looks like this, I don't think we can directly open the Alipay windows since stripe ask you to input the email and alipay account on the Strip page first. But can we default to the Alipay section rather than the Credit card section on the screenshot? 
![image](https://cloud.githubusercontent.com/assets/7925929/15950964/a7e54716-2e68-11e6-9194-6f66a9e898ae.png)

**Comment by p3rcya** [comment]
Also, do we have to have the email field? Can we remove it?
