### ISSUE TITLE
Desktop data cap alerts show even if we're pro

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4620]

**Comment by fffw** [comment]
It's caused by various conditions:

1. Lantern backend doesn't know if the current user is Pro or not.

2. `http-proxy-lantern` [always sets XBQ header](https://github.com/getlantern/http-proxy-lantern/blob/5bc1df4868fa36b690f28800425601471a7e4651/devicefilter/devicefilter.go#L88), even when it knows that [the connection is from a Pro user](https://github.com/getlantern/http-proxy-lantern/blob/5bc1df4868fa36b690f28800425601471a7e4651/listeners/bitrate.go#L81).

3. The Datacap is configured as startup parameter in `http-proxy-lantern`, instead of on user basis.

Ideally, the proxy server should still send XBQ header, but with a datacap of infinite greatness, but that adds complexity on the server side. The only feasible way is to have the client making sure it's free before showing notification. It can't rely on UI to provide such information.

**Comment by fffw** [comment]
We can, of course, call `/user-data` directly from backend to determine if current user is Pro, but @myleshorton @xiam @uaalto do you have better ideas?

**Comment by xiam** [comment]
This was a case that was already fixed, the UI was checking for pro status before showing the notification. Maybe something changed on the backend side, gonna take a look.

**Comment by myleshorton** [comment]
This is desktop notifications @xiam

**Comment by uaalto** [comment]
I think the "standard way" of knowing if a user is Pro or not is to ask the Pro server about it using `/user-data`, as you mentioned above.

**Comment by xiam** [comment]
> This is desktop notifications @xiam

Yes, @myleshorton. My test was:

1. Consumed all available bandwidth on my free account.
2. Bought pro.
3. Got the pro screen without the bandwidth notifications you're mentioning.

Can you provide a way to reproduce this problem?

**Comment by fffw** [comment]
@xiam I guess you were assigned a broken proxy so it never response with `XBQ

**Comment by xiam** [comment]
I think I have the XBQ header, my bar is full. If you or @myleshorton can reproduce this problem maybe you can try to see what's missing here: https://github.com/getlantern/lantern-desktop-ui/blob/master/js/components/DataCap.react.js#L27

**Comment by fffw** [comment]
@xiam The growl is shown [here](https://github.com/getlantern/lantern-pro/blob/fce2f546d2b6c652bf14213189a449441064a79a/src/github.com/getlantern/flashlight/app/bandwidth.go#L25), which should be irrelevant to desktop UI. Did you ever see it before upgradeing to Pro?

**Comment by xiam** [comment]
Oh no, never saw that, I'm running this on Linux from a remote host. Now I understand the part about it being "desktop notifications"...

**Comment by fffw** [comment]
If no objection, I'll continue with the plan: fetch /user-data before showing the growl.
