### ISSUE TITLE
Got plans in US dollar when the UI is in Chinese

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4627]
It requests `plans?locale=en-us`. Should configure Pro client with user selected language.

**Comment by p3rcya** [comment]
I don't know if this should be fixed. I think right now the prices goes with the system language? We might not want users to be able to change the price just by changing the language in the UI. Because we might have different price for different regions. And even now, the USD and RMB price have some differences. Later, when might even want to lock the price based on IP addresses AND languages.

**Comment by myleshorton** [comment]
Closing in favor of getlantern/lantern-desktop-ui#104 since it has a screenshot =)
