### ISSUE TITLE
The main page and all the other screens shows text that doesn't mean anything to the user

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4668]
![image](https://cloud.githubusercontent.com/assets/11394369/16022680/ec5c182c-316d-11e6-9b80-e0bb9b816125.png)

**Comment by fffw** [comment]
@sunshine19090  It happens when the language you selected has no translation file, and the fallback language `en-US.json` is also not available.

It should be fixed by https://github.com/getlantern/lantern-desktop-ui/pull/109, just need a new build.

In the meantime, you can switch back to English (the first item in language dialog) to let it show correctly.

**Comment by sunshine19090** [comment]
My language settings is in English already.

![image](https://cloud.githubusercontent.com/assets/11394369/16094581/a99288da-32f5-11e6-93b0-c19df52d1a5a.png)

**Comment by sunshine19090** [comment]
My language settings is in English already.

![image](https://cloud.githubusercontent.com/assets/11394369/16094609/d0baae56-32f5-11e6-8360-c0be0542e106.png)

**Comment by fffw** [comment]
@sunshine19090 thanks! I'll take a look

**Comment by fffw** [comment]
Oh I found out the reason. It's caused by https://github.com/getlantern/lantern/issues/4473 so though you selected another language, "English" is still the selected one next time.

A PR https://github.com/getlantern/lantern-pro/pull/33 is pending merge to fix it.

**Comment by sunshine19090** [comment]
working fine now.

**Comment by sunshine19090** [comment]
Leaving this open just in case this is in pending merge for other reasons.

**Comment by sunshine19090** [comment]
Looking good even after changing the language often.
