### ISSUE TITLE
UI: Desktop: Create default alert dialog when deauthorizing device from Account management screen

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4714]
@myleshorton mentioned this in the team meeting call today. 
when a user deauthorizes a device this alert should pop up. This is a stock alert, we can use this format for similar situations. 
![screenshot 2016-06-16 14 02 53](https://cloud.githubusercontent.com/assets/4400763/16127780/dfef1e30-33cb-11e6-95b5-c8b2bacde82c.png)
**Text:**
• "Deauthorize Device" Title: Roboto Medium(500), 18pt, #000000
• "Are you sure..." Dialog: Roboto Regular(400), 14pt, #000000, Line leading 21pt
• "CANCEL" and "OK" Buttons: Roboto Medium(500), 14pt, #00BCD4

**Elevation: 8px**

It should appear in the center of the screen like this:
![screenshot 2016-06-16 14 20 09](https://cloud.githubusercontent.com/assets/4400763/16128157/7a51d336-33cd-11e6-8b9c-14ce211935fc.png)

**Comment by myleshorton** [comment]
It seems like it might make sense to have a standard dialog design that supports displaying dialogs in lots of places, so I just want to make sure this is synced up with any other dialogs we might be creating @carsonefv and @xiam. I guess the only other one currently under discussion is the Lantern disconnection dialog, but maybe that's such a significant one that it warrants being special? Otherwise I just think we should standardize on dialogs in general that can then be used anywhere.

What do you guys think?

**Comment by carsonefv** [comment]
✓✓ @myleshorton
