### ISSUE TITLE
Log out button in account management screen 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4742]
@Derekf5 @myleshorton 
There should be a log out button on the account management screen. Currently, however my windows 10 is listed under authorized device. The screenshot is **after** I removed the windows 10 from the authorized device. And I can actually still use pro on this very windows 10. 

![image](https://cloud.githubusercontent.com/assets/7925929/16221517/1f749e2a-3748-11e6-94d1-0ccf96897ab0.png)

**Comment by Derekf5** [comment]
Yeah specs for that button are in #4684

**Comment by myleshorton** [comment]
Yeah I actually removed that because it seemed odd to have two sections for removing a device and to call it two things (is "log out" supposed to do something different from "remove"? if so what?).

The device name is definitely weird, though, and the fact that it didn't remove it from the list is weird too. I'll test more on Windows. The fact that you're still pro is logged at:

https://github.com/getlantern/lantern-desktop-ui/issues/131

**Comment by myleshorton** [comment]
Wait, also @p3rcya, so you authorized multiple devices and then removed Win10, is that right?

**Comment by myleshorton** [comment]
Oh wait, sorry, what is that "854..." device @p3rcya?

**Comment by Derekf5** [comment]
@p3rcya logout means you are logging out of the device you are currently on.  Remove is to logout of other devices that are authorized to use your account.

**Comment by p3rcya** [comment]
@myleshorton @Derekf5 Please use the design specified in #4684. We discussed a lot to settle on this. We want to differentiate log out and remove device. 

@myleshorton The weird name correspond to Android NOT windows 10. Windows 10 has been removed . Even though it's still logged in

**Comment by p3rcya** [comment]
@myleshorton The reason for "log out" is 
if the user click log out, the user is logged out of the current device and the account management page should disappear. This is not expected, if a user simply click remove.

**Comment by myleshorton** [comment]
This doesn't seem necessary for the MVP - adding to backlog.
