### ISSUE TITLE
[Mobile] send log page

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4870]
Currently on mobile, the send log doesn't allow user to describe the issue. We should have the send log page described in https://github.com/getlantern/lantern/issues/4869

Also we will change the language from send log to report issue

**Comment by atavism** [comment]
Hey @Derekf5, could you design the UI for this? This is pretty high priority because we have lots of users submitting logs but no way to filter by issue or for the user to provide an e-mail for us to follow-up (for those users unable to sign-up for Pro).

**Comment by Derekf5** [comment]
Yes @atavism i will work on it this weekend

**Comment by Derekf5** [comment]
Hey @atavism @p3rcya Let me know what you think about this.   Users should have to inlcude an email to report an issue, so if it is left blank we shoudl serve a "must include email" error.

Once the issue is succesfully submitted a snackbar should appear saying "Success, Thank you for reporting your issue."

@chipstehr how does the copy on this report an issue page look to you?

![reportissu](https://cloud.githubusercontent.com/assets/7864729/16896745/57c0ef3c-4b6a-11e6-844c-eaca520d2e59.png)

**Comment by p3rcya** [comment]
I suggest that the text box is mandatory as well. This will help reduce the amount of emails and encourage them to give us a clear description.

**Comment by p3rcya** [comment]
@atavism So besides the Chinese hardware type that might not be recognized, what about the plan status(Free or Pro)?

**Comment by Derekf5** [comment]
we can just include the free or pro status to ourselves. 

And agreed @atavism lets put in error in the text box saying "must provide description of issue" if users attempts to submit without filling in that field

**Comment by Derekf5** [comment]
Seems like we could also put a drop down menu on this screen for common issues to help separate/sort them on the back end, what do you think @p3rcya ?   what are the most common issues we are seeing from users?

**Comment by p3rcya** [comment]
Most common issues as below. Most those are specific issues that we are aware of and need to fix. I think we should provide in terms of more general terms, for example
1. Cannot circumvent even after turning it on
2. Cannot complete the payment 
3. Cannot log in
4. Spinning forever
5. others


----
expiration date wrong caused by invalid payment
https://github.com/getlantern/forum/issues/460#issuecomment-233117368

Stuck at verification screen https://github.com/getlantern/lantern/issues/5016
https://github.com/getlantern/lantern/issues/5021


Nothing happens when click "Continue to check out screen" https://github.com/getlantern/lantern/issues/5027

**Comment by Derekf5** [comment]
Thanks @p3rcya. @atavism will having those issues as a dropdown help you with sorting thru logs on the backend?

**Comment by atavism** [comment]
Great idea, @Derekf5! Would definitely make it easier to categorize/sort through user issues. That looks like a good list to me too. We'll just have to make sure to get those strings in Transifex. 

```
- Cannot circumvent even after turning Lantern on
- Unable to complete purchase
- Unable to sign in to Pro account
- Spinning Forever
- Other
```

If the user selects ``Other``, there could be a separate text field to add to a description?

**Comment by Derekf5** [comment]
Cool i will redesign that page, @chipstehr how do you feel about the wording of those issues for users?

**Comment by chipstehr** [comment]
1. Cannot access blocked sites even after turning it on
2. Cannot complete the payment 
3. Cannot log in
4. Will not load
5. Slow 
6. Cannot link devices

**Comment by Derekf5** [comment]
Thanks @chipstehr ! LGTM

**Comment by p3rcya** [comment]
4. should be explicit, maybe Some page will not load and stuck at the spinning

**Comment by chipstehr** [comment]
@p3rcya #1 should be specific, or #4 ?

**Comment by p3rcya** [comment]
＃4 (Github auto-corrected 4. to 1. )

**Comment by chipstehr** [comment]
1. Cannot access blocked sites even after turning it on
2. Cannot complete the payment
3. Cannot log in
4. Will not load, loading spinner spins endlessly. 
5. Slow
6. Cannot link devices

**Comment by p3rcya** [comment]
looks good

**Comment by Derekf5** [comment]
Hey @atavism @p3rcya @chipstehr here is the new spec sheet for the report an issue screen.
@atavism the two new icons  (black error icon, and drop down error) are in our shared dropbox.

When a user clicks the text field and the keyboard pops up we should center the text box on screen so it is visible to the user.  Let me know if this makes sense Todd.  The first image is the view a user will see when they arrive at the screen.  the second image is what the dropdown should look like when open.

@chipstehr @p3rcya i had to shorten the issues a bit for mobile for them to fit. 


![reportissue1](https://cloud.githubusercontent.com/assets/7864729/16955159/a97b225a-4da1-11e6-87bc-670df7cb1b57.png)
![report-issue2](https://cloud.githubusercontent.com/assets/7864729/16955164/ae7bb3a0-4da1-11e6-86cc-db3d8a6fa88d.png)

**Comment by Derekf5** [comment]
Please add "other to the list @atavism

**Comment by atavism** [comment]
New strings for this are up on Transifex, and I sent @Derekf5 a build to review.

**Comment by p3rcya** [comment]
I did the translation, however @atavism @Derekf5 @chipstehr 
I think those two issues are duplicate. If a user cannot link device, then he should use that device to submit a Cannot sign in issue. Having two of them are just confusing, especially in Chinese because I call link a device "sign in"
<item>Cannot sign in</item>⏎
<item>Cannot link devices</item>⏎

**Comment by p3rcya** [comment]
We should also add a "App Crashes" choice. Even though most of crashes would happen right after launch so that user cannot even submit logs this way, it's still useful for crashes after some time

**Comment by atavism** [comment]
Ok @p3rcya I added "App Crashes" if you want to translate that one as well.

**Comment by p3rcya** [comment]
@atavism what about the duplication mentioned earlier?

**Comment by p3rcya** [comment]
done @atavism

**Comment by p3rcya** [comment]
@atavism In the backend, we should have a way to distinguish Pro/Free users easily without looking at the log
