### ISSUE TITLE
3.0.7 flagged by windows, kaspersky, 360,金山毒霸,bitdefender,McAfee

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4875]
User reported

**Comment by p3rcya** [comment]
@myleshorton This is pretty bad. Many users have asked whether this is fake on the forum or emailed me directly. Since we have no announcement and we're charging people, this is very suspicious considering there are so many fakes. 

In the future, we need to get all major one cleared before releasing them

**Comment by xiam** [comment]
An [user in the forums](https://groups.google.com/forum/#!topic/lantern-users-en/KenL3YTXYNQ) also reported problems with Kaspersky

![vreport](https://cloud.githubusercontent.com/assets/385670/16707915/e5ffdef4-45a5-11e6-822e-3bbc2bfa8893.png)

**Comment by sunshine19090** [comment]
I will send out 3.0.6 for whitelisting. 

@fffw Can you please upload the files for kaspersky?

**Comment by p3rcya** [comment]
https://www.virustotal.com/en/file/dcf08b2557ceb4665e332e4e959c0d4c2518cb5c09038ec9da4ee6201049bcfe/analysis/
