### ISSUE TITLE
[unable to reproduce] Accessing PayPal failed with "a network change was detected" in Chrome

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4902]
I haven't done much research into it yet, but I suspect this might be because I'm now getting multiple proxies and my IP is changing.  I looked into the log, and sure enough my first request to PayPal went through a different proxy than my 2nd.

Note - I was able to recover from this error by refreshing, but its still worth looking into.

**Comment by oxtoacart** [comment]
Not super useful, but here's on thread to pull on - http://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome

**Comment by myleshorton** [comment]
Interesting @oxtoacart thanks. So it seems like maybe once we hit X site with X proxy, have to stick with it for awhile or something. There's probably a simpler solution though.

**Comment by oxtoacart** [comment]
I see this pretty reliably on www.nytimes.com.

```
Failed to load resource: net::ERR_NETWORK_CHANGED
```

**Comment by oxtoacart** [comment]
It looks like ERR_NETWORK_CHANGED happens if Chrome detects that the IP address has changed.

https://cs.chromium.org/chromium/src/net/quic/quic_stream_factory.cc?q=ERR_NETWORK_CHANGED&sq=package:chromium&dr=C&l=1331

**Comment by oxtoacart** [comment]
Maybe Chrome is using an internet server to determine its address, and we're proxying traffic to that internet server.

**Comment by oxtoacart** [comment]
It looks like the implementation of this is platform specific, so it's possible that this is isolated to OS X.

**Comment by p3rcya** [comment]
Some foreign trade users complained on this too

**Comment by oxtoacart** [comment]
BTW, I'm seeing this all the time.  Can't imagine that it helps performance/UX.

**Comment by fffw** [comment]
I didn't experience this issue at all because Lantern was always using the same proxy (the one with smallest `EMADialTime`). The `QualityFirst` strategy does work well if one proxy is quicker than others.

OTOH, the `Sticky` strategy keeps using same proxy unless it fails to dial for once. it should solve this issue but if one slow proxy is selected at first, Lantern will stick with that one.

A quick fix would be an improved `Stickey` strategy: When comparing two dialer, always choose the one with more `ConsecSuccesses` (mostly used), unless its `EMADialTime` is more than, say, twofold of another one. Actally that's the goal of `Weighted` strategy, I just lost myself when implementing it.

Per site sticky route is still appealing to fully utilize user's bandwidth, say, watching YouTube while downloading large files. We can borrow mature algorithm from load balancer (sticky session) or [link aggregation](https://en.wikipedia.org/wiki/Link_aggregation) world but our situation is more complex (though not that mission critical).

**Comment by myleshorton** [comment]
I like the idea of an improved sticky strategy @fffw. Moving this to the top of the backlog, as I do think it's very important and quite possibly related to pro users experiencing Lantern as slow.

**Comment by oxtoacart** [comment]
+1
