### ISSUE TITLE
Who is p3rcya, and what happened with lantern?

### ISSUE THREAD

**Issue by b-z** [getlantern/lantern#4944]
After the appearance of Lantern 3.x, the 2.x version became inefficient. And the "getlantern" repository seems to be sold to a Chinese user @p3rcya .

Why can't we use the P2P version lantern any more?
And what's the difference between this new lantern and other VPNs?

I've canceled the Star of this program, and wish the real lantern come back one day.

**Comment by jxmlhdf** [comment]
answer is here  #4942

**Comment by b-z** [comment]
i see..
so i'm considering buying a VPS now

**Comment by rookieInn** [comment]
@b-z install a VPN on VPS by youself?

**Comment by myleshorton** [comment]
@jxmlhdf and @b-z the mission of Lantern is the same as it always has been, namely to end censorship on the internet. At every phase we have done what we believe to be the best path towards accomplishing that goal. P2P architectures work well for certain things, but for typically proxying pure P2P approaches are simply slow, and speed is the one thing users care about the most.

The optional paid version of Lantern is a part of that. In order to continue building the best software we can, we simply cannot make it completely free forever. The reality is that it costs money to build all great things. Even more purely open source projects, like Linux, in practice get a great deal of their real work done by full time staff at places like IBM.

So the repository has not been sold to anyone, and @p3rcya works with our team. In any scenario, however, I and the Lantern team are fully committed to building the best possible software we can for you to keep the internet free.

**Comment by b-z** [comment]
@myleshorton thanks for answering.
[手动微笑]

**Comment by myleshorton** [comment]
You are very welcome @b-z. Also, please know that we take your opinion very seriously when determining the direction of Lantern. If you think there is a better path for us to follow, we are always interested to hear.

**Comment by SQZSoft** [comment]
@myleshorton thanks for all of members hard working in the Lantern team. Kindly recommend following business model for the Lantern team to continue the product development:

Model 1: For most of Chinese users, will not purchase 1 year service product, especially for the bypass "GFW" products, recommend to add option to purchase the Pro version by 1 month, 2 month, 3 month 

Model 2: Add ads (like adMob...) in the free version, and add the Google Play In-App Billing to upgrade to Pro plus remove the ads. The 3.0.4 payment system is bad experience for me, and most of people don't trust apps which use their own payment system (security...)

Model 3: Add donation page, can be $1, $2... then the donor will get some discount to upgrade to Pro

**Comment by p3rcya** [comment]
@SQZSoft May I ask if you're a Chinese user yourself?  
If you were a Chinese user, you would know that Google Play (including IAP) doesn't work in China. And most users do want to use their own payment method. Most Chinese users are not privacy aware and do not know how to speak English or have a foreign credit card to use Google Play.
You would also know that few Chinese users will donate. No disrespect. But I have data on donation based products in China. And let's just say it probably cost more to maintain the donation page.

As for 1, users now can share their referral code to their friends and get 1 month or 3 months of Pro. And You claim that users will not purchase 1 year product is dubious at best. Take a look at domestic VPNs.

**Comment by p3rcya** [comment]
@SQZSoft Thanks for your suggestions, of course and we do welcome further suggestions from you. But we did do our market research before deciding a business model. No disrespect @SQZSoft, but I really think your alternative model is not suitable to China

**Comment by EdwardAutumn** [comment]
@p3rcya since you mentioned this,i have to say make lantern commercial now is definitely not a good strategy, because it just has too many problems and apparently you group is short hand,if you can't fix bug quickly,then the user have to suffer from what  they actually paid for,like me.for the record I'm totally willing to pay for lantern,but I really hope it could working at least.

**Comment by p3rcya** [comment]
@EdwardAutumn Thanks for your support. Indeed, we have lots of bugs at the moment. We would not have noticed many of them however, if we didn't put it out to the public. In fact, we didn't post Lantern3 to https://getlantern.org because of those bugs. Users who purchased Lantern Pro before the official release on https://getlantern.org will get one additional month free to thank them for tolerating our bugs.

**Comment by EdwardAutumn** [comment]
@myleshorton I have to say I support your team make money from lantern,because I don't believe anyone of you come from the avengers or justice league, everything comes with price,it would money or something else, people who didn't realize that is either  a kid or a fool.

**Comment by SQZSoft** [comment]
@p3rcya Yes I'm Chinese, and I'm facing a lot of interferences by the GFW, and I tried a lot of VPNs for the last two years, so let me explain the reasons for my recommendations:
For Model 1, you can see most of VPN ISPs supports pay 1 month - 3 month plans, usually 15-20RMB for just pay 1 month. Because most of the bypass GFW products not really stable, I never see these products can stable working or survive more than 1 year, even Lantern

**Comment by SQZSoft** [comment]
@p3rcya Yes I'm Chinese, I'm facing a lot of interferences by the GFW, and I tried a lot of VPNs for the last two years, so pls let me explain the reasons for my recommendations:

For Model 1, you can see most of VPN ISPs supports pay 1 month - 3 month plans in China, usually 15-20RMB ($2-$3) for even just pay 1 month. Because most of the bypass GFW products are not really stable, I never see these products can stable working or survived in more than 1 year, even Lantern is completely not working for me about 3 days. I'm not saying Lantern will not working, but more choices for customers (remember paid users are "CUSTOMERS") are better user experiences, and more people will willing to pay

For Model 2, the users can use the In-App billing after the Lantern connected, because their location is showing not in China for Google servers. Most of people come to use Lantern are not beginner users, privacy is really concerred. Also use the IAP can reduce a lot of work / risk for Lantern team, plus you can get very good service from Google (Like sales report...). Use ads is much better than the current new subscribe, which obviously has politic things get involved. (The Lantern can popup an Interstitial ad when the user enabled it, and display some banner on bottom)

For Model 3 is for global users, not only for Chinese, that's the reason I post in this forum instead of the Chinese Lantern forum

**Comment by myleshorton** [comment]
Thanks so much for your thoughts on this @SQZSoft. We decided to start with only the 1 or 2 year plans, but we may introduce monthly payments in the future. The big issue we had with monthly payments was that most Chinese also don't like to auto-renew, and it seemed inconvenient for users to manually renew every month.

The IAB idea is very interesting @SQZSoft, and we'll be discussing this more with @WolfLantern and @chipstehr as well.

**Comment by SQZSoft** [comment]
@myleshorton @p3rcya thanks for both of your replies, BTW, kindly remind that if Lantern supports Alipay to process payment, soon or later the Alipay payment account will be blocked, and the Lantern team will lose the money which had not withdraw, then many payment issues / complains will come from customers...

**Comment by myleshorton** [comment]
Thank you @SQZSoft!

**Comment by jxmlhdf** [comment]
@myleshorton  With all due respect, The issue #494x has been closed as we truly understand the sincerely explanation from you and the team. In my opinion, The fundamental problem with Lantern now is that  the team seems like hardly to determine which of the direction for Lantern to carry on. Second, Neither free nor Pro version are seems to works in China currently, the part of the reason is probably due to the GFW is implemented more aggressive approach to block lantern recently.Therefore, the team should figure out how to make the software more efficient and faster speed to create the beautiful user experiences once again before determine the in which steps to follow. This is also the key point that why most of users is complaining the teams right now. Please do focus on how to improve circumvention resistance approach itself other than consider whether offer more version! Lastly, most of users hereby request your team fire one of your team member so-called "p3rcya", he is absolutely dame the image of Lantern team at this moment.

**Comment by myleshorton** [comment]
Thank you @jxmlhdf. We completely agree about making sure that Lantern just works, and I also agree that building this second version took time away from making sure that Lantern just works. I assure you that is our #1 priority going forward, however, and we will ultimately be able to focus on it even more with a sustained source of revenue from Pro. We have experienced a wide variety of issues over the past several days that have contributed to Lantern not working as well, including increased blocking and a database outage during peak times yesterday. We should have it back and fully operational again soon, however, and I encourage you to try the 3.0.6 version just released at:

https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.6.exe
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.6.dmg
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.6.apk
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.6-32-bit.deb
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.6-64-bit.deb

With regard to the image of Lantern and our interactions with you on these messages, I sincerely apologize if anyone on our team has not been anything but completely respectful to you and other users. That would not be true to the Lantern vision and intent, and please feel free to elaborate on any issues that have arisen.

**Comment by p3rcya** [comment]
@jxmlhdf "most of users hereby request your team fire one of your team member so-called "p3rcya" Can you give one example besides yourself where a user is request me being fired? I've replied to hundreds of issues on the forum and I'm yet to see one.  On the contrary, many users call me bro when asking me questions (https://github.com/getlantern/forum/issues/391#issuecomment-231266114) and thanks me profusely when I replied to their requests. 

Please specify how I damage Lantern's image please.

**Comment by EdwardAutumn** [comment]
@myleshorton the link is not right.

**Comment by fffw** [comment]
@EdwardAutumn please try alternative link https://s3.amazonaws.com/lantern/lantern-installer-3.0.6.exe. Rename the extension for other platforms

**Comment by fffw** [comment]
No request for removal actually. Users may misunderstand you but we know you are the famous and passionate @p3rcya

**Comment by p3rcya** [comment]
@fffw He is not a fucking user, he sells VPN for a living and was banned by Adam https://github.com/getlantern/lantern/issues/3124#issuecomment-139447409
