### ISSUE TITLE
spinning problem affects Pro users

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4945]
Getting more info https://github.com/getlantern/forum/issues/395
Did the UI load from the free servers and only after the UI loads will Lantern use Pro servers to proxy?

[9:09]  
I saw multiple reports on this already. They used a VPN to purchase, or purchased where Lantern was not blocked

**Comment by JohnJZ** [comment]
Yes, it was loooooading..., and finally failed, saying that "我们无法连接到蓝灯的服务器"。But I really have no idea whether it was starting from the free server or the Pro one, since I don't know how to tell.

I m using Opera, Win 7. And here goes the log 
[JohnZ log.txt](https://github.com/getlantern/lantern/files/353592/JohnZ.log.txt)

**Comment by p3rcya** [comment]
Log https://github.com/getlantern/forum/issues/528#issuecomment-231930190
