### ISSUE TITLE
4 hours ago

### ISSUE THREAD

**Issue by kxkxkx** [getlantern/lantern#4949]
4 hours ago

**Comment by afboyxiyang** [comment]
大傻B

**Comment by NAVrasZ** [comment]
但是不知道免费版的限制如何，如果和其他收费vpn一样“免费试用版”几乎不能用就太糟了。
有的人拿着免费高效的翻墙去糟蹋到最后大家都不能用了的确可恶（例如一些ss节点的遭遇），对有需要且有支付能力的人收费并提供更好的服务是正确的。
国内未成年大部分估计都没有支付线上商品的能力（父母限制，尤其是购买“翻墙软件”），但我不觉得他们被封是“活该”，搜索不靠谱广告占首页、想要看视频先2分钟广告、找不到专业性的知识和资源，这些本就不应该是这样，lantern“open Internet for everyone”,希望这句话不是噱头，开发者能对普通版和pro版都有负责的态度。lantern之前一直免费却稳定，我相信他们。（issues里的伸手喷子神烦，例如楼上那位素质，这是GitHub不是某吧）
题外话，“秒杀vpn”名字太浮夸（个人不喜欢这种宣传方式，不知道他们是模仿还是拍脑门想的），安卓新闻流意义不大（如果是某国的赞助要求当我没说..）

**Comment by EdwardAutumn** [comment]
这边都是英文区，各位请到中文区讨论，老跑到英文区发中文就是没素质的表现。please speak English at this section.

**Comment by NAVrasZ** [comment]
@EdwardAutumn 

> 这边都是英文区，各位请到中文区讨论，老跑到英文区发中文就是没素质的表现。

I thought "issues" are made by GitHub for everyone,correct me if i'm wrong.Plus,"English" has its own section too,why "issues" become "英文区"?
And you say us"没素质",such a definition is rude and discriminational,don't you think?
It's a little annoying,but I'll post in Chinese section if I have to say something in Chinese next time.

**Comment by EdwardAutumn** [comment]
@NAVrasZ  You are just that kind of person who is full of himself are you,https://github.com/getlantern/lantern,the link right here says very clear,If you're looking for help, please visit below user forums:

| English | 中文 | فارسی | français

if you really care ,you wouldn't be here argue with me about this and i'm really not interested how you thought,so please stop explaining it to me.

**Comment by NAVrasZ** [comment]
@EdwardAutumn With all do respect,I mean no offense,what makes you think that bro?It's a common way people say things in the forum(well at least in a forum).Though a little annoying,but I mean objective,i'm truely sorry if any misunderstanding.
Let's put out the fire first please,it doesn't sovle the problem.
OK,the link related to the "中文"section is “getlantern/forum”，so it‘s actually forum not “issues”，that's why English got theirs(or it would be unfair right?)
And issues isn't divided via the language.
Ps:it's wrong to put meaningless post in "issues" though,but I tried to make this topic meaningfull by posting some whatever the thing is (advice,that is),i'm kinda regret this now,people may not see it because of the topic..

**Comment by EdwardAutumn** [comment]
@NAVrasZ I apologize for my attitude,let's end this discussion,agree or disagree.

**Comment by NAVrasZ** [comment]
@EdwardAutumn agree ;)
