### ISSUE TITLE
3.0.7 spinning problem at the main UI

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#5039]
log https://github.com/getlantern/forum/issues/658

**Comment by p3rcya** [comment]
More with log https://github.com/getlantern/forum/issues/663

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/658

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/819#issue-167270493

**Comment by p3rcya** [comment]
He removed Lantern completely and reinstalled 3.0.7 but still encountered the spinning problem https://github.com/getlantern/forum/issues/832#issuecomment-235164330

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/841#issue-167596043

**Comment by p3rcya** [comment]
Pro log https://github.com/getlantern/forum/issues/835#issue-167548651

**Comment by p3rcya** [comment]
More log https://github.com/getlantern/forum/issues/865

**Comment by myleshorton** [comment]
Moving this to the top of the backlog @p3rcya. Not sure it's the top issue not in TODO, but just want it up near the top.

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/865#issue-168265107

@myleshorton yeah, this should be one of the top

**Comment by p3rcya** [comment]
More (no log yet) https://github.com/getlantern/forum/issues/519#issuecomment-236405950

**Comment by p3rcya** [comment]
No log yet https://github.com/getlantern/lantern/issues/5120

**Comment by p3rcya** [comment]
XP not log yet https://github.com/getlantern/forum/issues/923

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/934#issuecomment-238070806

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/920

**Comment by myleshorton** [comment]
@sunshine19090 also experienced this, and I'm also able to get it periodically on Safari.

**Comment by myleshorton** [comment]
Could easily be related to some of the caching issues we've seen as well.

**Comment by myleshorton** [comment]
Ha -- I actually just got this in Edge too @p3rcya and @fffw. After I linked a device, the welcome to pro screen popped up. I clicked "Continue to Pro" and got this:

![image](https://cloud.githubusercontent.com/assets/1143966/17504621/6fb25386-5daf-11e6-8c9a-fcc0b2f7f7e3.png)

**Comment by myleshorton** [comment]
Interestingly I actually did not become pro after refreshing either. Checking logs.

**Comment by myleshorton** [comment]
OK -- if I refresh again, then I become pro.

**Comment by myleshorton** [comment]
In the logs, Lantern was unable to connect to one of the pro proxies even though from the command line that proxy appears to be accessible and having no issues.

**Comment by myleshorton** [comment]
Hey @p3rcya does just refreshing the page often work in these cases?

**Comment by myleshorton** [comment]
Presumably that was hanging on that subsequent `user-data` call @fffw, but it's curious that I didn't immediately become pro after my first refresh. It also seems like all of those calls should timeout with some error eventually and shouldn't just show the spinner forever.

**Comment by myleshorton** [comment]
@oxtoacart you might also be interested in this one.

**Comment by p3rcya** [comment]
@myleshorton No. They're stuck on the verification code page and it happens with every try. Log https://github.com/getlantern/lantern/issues/5134#issuecomment-238445923

**Comment by myleshorton** [comment]
In both my and @sunshine19090's cases we have a lot of timeout errors in our logs hitting X server. In both cases, though, those servers are accepting connections very quickly! It's almost like there's either some misconfiguration where we're not properly authenticating or the timeout is misconfigured and is timing out almost immediately @fffw and @oxtoacart.

**Comment by myleshorton** [comment]
> @myleshorton No. They're stuck on the verification code page and it happens with every try. Log #5134 (comment)

But I mean does refreshing the page get rid of the spinner?

**Comment by p3rcya** [comment]
@myleshorton Refreshing at any page will kick user back to the main UI. As the user haven't submitted to verification code (they got spinning after enter the email), they will just have to go the authorize device screen again. And the spinning happens with every try

**Comment by myleshorton** [comment]
Gotcha @p3rcya thanks.

**Comment by oxtoacart** [comment]
@myleshorton 

> timeout errors in our logs hitting X server

Which server is this?  Proxy, pro, ... ?

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/960

**Comment by myleshorton** [comment]
> Which server is this? Proxy, pro, ... ?

One of the pro servers allocated after becoming pro.

**Comment by p3rcya** [comment]
this user said he encounters the problem after updating to 3.0.7 without uninstalling previous version. But he solved it by uninstalling with QQ cleaning (which probably delete all files) then installing 3.0.7 again https://github.com/getlantern/forum/issues/960#issuecomment-238735441

**Comment by fffw** [comment]
The most direct cause would be network issue.

An imaginary scenario if the free proxy is blocked or has issue connecting:

1. Each dialer takes 30s to timeout, which adds up to 90s before failing.
2. Edge times out in 60s or so.
3. Lantern pro js client retry 3 times, which takes 180s at most.
4. User believes it spinning forever (or desktop-ui doesn't show correct messages, testing on Edge)

It happens more often when linking devices because `POST` requests are using `ChainedThenFronted` instead of `ParallelPreferChained`, so if proxy doesn't work, it times out in 100% cases.

What we did in https://github.com/getlantern/lantern/issues/5016 should mitigate it in this case.

**Comment by fffw** [comment]
On Edge, the spinner hides after several minutes without any message showing on the UI when the proxy is inaccessible.

**Comment by myleshorton** [comment]
I wonder if this might be related to some of the balancer issues @oxtoacart was experiencing @fffw. Seems like those changes could at least help, as the odd part about this entire issue to me is it's unclear why users would have such frequent issues accessing their proxy.

**Comment by fffw** [comment]
OK, I finally encountered the spinner for about 50s with a `/user-data` call. If it's POST call, the wait time will be doubled.

The proxy could be dialed, but read/write operation couldn't complete due to something like serious link congestion. Idletiming closed the connection after 45s. `proxied` finally switched to the dual dialer and got the response quickly from chained proxy this time.

Not just Pro API, any site would suffer from this kind of situation. If it takes up to 3 times to dial proxy, the wait time can be increased to minutes.

Attatched logs (removed irrelevant items).
[eof-caused-spinning.txt](https://github.com/getlantern/lantern/files/422131/eof-caused-spinning.txt)

**Comment by fffw** [comment]
The most direct fix should be to dynamically `SetDeadline`, so read/write can fail fast and retry.

Another improvement is to track more metrics of each proxy independently, include bps and read/write errors.

**Comment by myleshorton** [comment]
It seems strange to me that the proxy would all of a sudden be completely unable to read any data whatsoever @fffw and/or that the client would be unable to write any data. I can imagine it if you've actually lost your network connection for some reason, but that's about it. 

I wonder if this would happen far more frequently on a spotty connection. I also wonder if we're trying to be too smart here. Most browsers, for example, seem to have really solid retry logic these days. It might make more sense for us to do something like the following:

1) If we fail to connect to a proxy once, run some sort of check to determine if the network is failing in general (or possibly run a quick check to see if all proxies are failing)

2) Do nothing -- just wait for the browser to try again.

**Comment by fffw** [comment]
We need to investigate if there's potential code bug here, but it can happen frequently in a highly congested network. In chapter 5 of https://tools.ietf.org/html/rfc6298, the RTO backs off if times out. For an initial RTO of 3s, not receiving ACK 3 times would add up to 3+6+12+24=45s.

The idea of `SetDeadLine` dynamically is to fail fast so browser can retry, or browser will wait for at least 45s without doing anything.

Bear in mind that congestion / flow control on the international exit can be catastrophic and highly dynamic. It's quite usual when you downloading a S3 file from the Chinese VPS, the speed starts with hundreds of KB/s, then suddenly stalls for several minutes, and never reaches 10KB/s again. That's why "TCP accelerating software" is popular: send multiple copies to reduce the impact of packet loss.

**Comment by p3rcya** [comment]
more https://github.com/getlantern/lantern/issues/5189

**Comment by fffw** [comment]
The log file for https://github.com/getlantern/lantern/issues/5189 shows following sequence:

0m6s: start dialing Pro API server (for `POST /user-create` call?)
1m6s: 1st attempt timeout, try again using a new proxy from newly fetched config
2m6s: 2nd attempt timeout. 
2m6s: skip 3rd attempt for same proxy
2m6s: try fronted
2m9s: fronted succeeded
2m9s: dial Pro API again, still with `chained` first. <- [1]
3m9s: Lantern stopped

[1] interesting here because the second call should be `GET /user-data`, which should dial fronted in parallel.

**Comment by myleshorton** [comment]
> Bear in mind that congestion / flow control on the international exit can be catastrophic and highly dynamic. It's quite usual when you downloading a S3 file from the Chinese VPS, the speed starts with hundreds of KB/s, then suddenly stalls for several minutes, and never reaches 10KB/s again. That's why "TCP accelerating software" is popular: send multiple copies to reduce the impact of packet loss.

This is super interesting @fffw. It would be surprising to experience this on the network in the US, but maybe not in China. Having an acceleration option seems interesting.

I'm still surprised to be seeing so many failures for this user, though. It seems like there are a few things here:

1) We should probably switch modes/proxies even more quickly (maybe using the dynamic timeout idea).
2) We should figure out if those proxies are actually blocked or what's going on exactly with them. I'm still surprised if they're really just be experiencing that much congestion, but maybe that's possible in peak times?

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/files/436291/lantern.TXT

**Comment by p3rcya** [comment]
@myleshorton Many users reported that they cannot open a webpage during peak time while they can watch 1080P youtube after midnight.

**Comment by orbancanon** [comment]
Same problem at https://github.com/getlantern/lantern/issues/5210#issuecomment-242380919

Basically, if Lantern has trouble accessing the proxy, any POST request would timeout finally before having a chance to try DDF. @fffw

**Comment by p3rcya** [comment]
This user said he could use it but then it started to spinning for half an hour https://github.com/getlantern/forum/issues/1099#issue-173123014

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/1122
User report:
Lantern was fine before. But today it encountered spinning. I have to enable VPN to stop spinning. After closing the VPN, Lantern shows ON, but it's not useful. I uploaded two logs, when during spinning, the other after using VPN to enable Lantern but after closing VPN, cannot access any foreign site.

不知道怎么回事,前些天用着好好的,今天打开后一直转圈.学校的网有限制前些天也没事,我用同学买的别的vpn然后才能不转圈,然后关闭同学的vpn后虽然显示蓝灯已经开启但是没有用.下载最新版后是没办法登录到专业版的.上传两个日志文件,一个是开启同学vpn之前打开蓝灯的情况停留在转圈,一个是开启同学的vpn之后正常登录蓝灯但是关闭同学vpn只保留蓝灯但是不能访问国外网站的日志.

**Comment by p3rcya** [comment]
No log yet https://github.com/getlantern/forum/issues/1139

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/1167#issue-174447177

**Comment by fffw** [comment]
A recent observation shows that Chrome took up to 7.5 min to fail a POST request to a non-exist endpoint, though `pro/proxy.go` got the 404 result in 3m. It looks like that Chrome just discards the connection if it takes too long.

**Comment by p3rcya** [comment]
More log https://github.com/getlantern/forum/issues/1226

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/1242

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/1249#issue-176172801

**Comment by p3rcya** [comment]
more https://github.com/getlantern/forum/issues/1264

**Comment by p3rcya** [comment]
log at 3.2.0 spinning https://github.com/getlantern/forum/issues/1382#issuecomment-249355565

**Comment by p3rcya** [comment]
3.2 log https://github.com/getlantern/forum/issues/1404#issuecomment-249764090

**Comment by myleshorton** [comment]
formerly was given 3 story points.
