### ISSUE TITLE
Run IP scanner again

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5071]
Our domain fronting IPs get pretty stale -- we should run it again.

**Comment by myleshorton** [comment]
Code is here:

https://github.com/getlantern/lantern/blob/cfscanner/src/github.com/getlantern/cfscanner/cfscanner.go

**Comment by myleshorton** [comment]
node is here:

https://cloud.digitalocean.com/droplets/7061424/graphs

**Comment by myleshorton** [comment]
We need to do the following:

1) Run the binary on the scanner machine
2) Update https://github.com/getlantern/lantern_aws/blob/master/salt/update_masquerades/masquerades.txt with the output file from that binary
3) commit, update.py in donyc3, and hscloudmaster

**Comment by myleshorton** [comment]
Hey @aranhoide I just committed the new masquerades file -- you mind just deploying it? I forget how to do that =).

**Comment by myleshorton** [comment]
Took about 4 hours to run! That was setting the parallelism to 200. Could probably do 1000. I also just committed a change to cfscanner.go that just reduces the dial timeout to speed things up since we definitely don't seem to have any shortage of ips.

**Comment by myleshorton** [comment]
So one major oddity I remember seeing before -- running genconfig.bash on my home machine directly after generating this new masquerades.txt file creates all sort of errors with mismatched domains and such. Not sure why.

**Comment by aranhoide** [comment]
@myleshorton :  TBH I never waited for the scanner to complete.  I only grabbed the output file as soon as it had enough masquerades (some 10k, IIRC), which happens quickly enough, and left it running in the dedicated VPS just in case I needed more later.

IIRC, there was some duplicate verification between the scanner itself and genconfig.bash.  For some reason which I can't remember, when I repurposed the Cloudflare scanner to work with CloudFront, I removed this repeated verification, so it's expected that many of the masquerades output by the scanner are somehow invalid.  These will be filtered out by genconfig.bash and enough remain, so all should be fine.

**Comment by aranhoide** [comment]
@myleshorton: I've just deployed the new masquerades.txt.  After having checked that in to lantern_aws master, it's only doing the usual `bin/update.py` and `bin/hscloudmaster.bash` dance.  The cloudmaster to deploy it to is `donyc3`, which is the default one.

**Comment by aranhoide** [comment]
@myleshorton I've just realized that maybe you meant deploying it as in running immediately what would otherwise have to wait for the daily cron job time?  I'm doing that as I write this.  One thing I'm noticing is that the masquerades.txt you uploaded has ~164K masquerades, which is about 16x what it used to be IIRC.  I'm concerned about the size of the resulting cloud.yaml.gz and global.yaml.gz.  If it's too big I'll truncate masquerades.txt and retry.

**Comment by aranhoide** [comment]
It might be a good idea to add a `maxmasquerades` argument to genconfig, and have it stop as soon as it has processed that many valid ones.

**Comment by aranhoide** [comment]
Indeed, `global.yaml.gz` grew from 46261 to 734979 bytes (almost 16x) with the new masquerades.txt, and the uncompressed `cloud.yaml` went from 202K to close to 8MB (!).  I'm not sure whether this will cause many problems in practice, but since I need to go unavailable for a few hours I'll lean on the safe side and push & deploy a masquerades.txt truncated by a factor of 10.  We can talk this later.

**Comment by myleshorton** [comment]
Issue moved to [getlantern/lantern-internal #354](https://github.com/getlantern/lantern-internal/issues/354) via [**ZenHub**](https://www.zenhub.com/)
