### ISSUE TITLE
Only send a sample of error logs to Loggly

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5089]

**Comment by oxtoacart** [comment]
We're on a 10 GB plan and we're sending 500 GB per day.  Sampling would help settle that, and should be an okay solution since we only ever look at the fat part of the distribution anyway.

**Comment by oxtoacart** [comment]
To test, you'll need to run from the command-line.

First, run with sampling disabled:

`./lantern -loggly-sample-percentage 0`

You should see a line like this in the log:

`Jul 26 18:25:56.559 - 0m0s DEBUG flashlight.logging: logging.go:220 DeviceID hDg1WzFA not being sampled for Loggly`

Then, run with sampling enabled:

`./lantern -loggly-sample-percentage 1`

You should see a line like this in the log:

`DEBUG flashlight.logging: logging.go:223 DeviceID hDg1WzFA will report errors to Loggly`

By default, we're only sampling 0.5% of devices, so if you run Lantern without the `loggly-sample-percentage` flag, you have a 99.5% chance of seeing the message that says we're not being sampled for Loggly.  Since the device ID doesn't change for a given machine, you'll always get the same result.

**Comment by fffw** [comment]
I'm a bit worried that only 0.5% of samples may not reveal the overall situation. Loggly events are also not evenly distributed. Take a look at [this example](https://bravenewsoft.loggly.com/search/?terms=&from=-1d&until=now&source_group=13316&savedsearchid=171399&newtab=true&tabname=HTTP%20Proxy&savedsearchid=171399&isfav=True&searchorder=desc#terms=json.extra.version%3A3.0.7&from=2016-07-27T00%3A59%3A48.982Z&until=2016-07-28T00%3A59%3A48.982Z&source_group=&filter=json.message%3Bsocket%3A%20too%20many%20open%20files&filter=json.extra.instanceid%3BmFrr4zOP): Single client generated 467K of events in less than an hour, while most of them are errors dialing Loggly.com! That single client would exceed our total volume if it's in the sampled group.

I suggest we introduce time based sampling, say, supress all successive events in 5 min duration. That would cap the total events to Loggly while taking all clients into account. We can use both sampling method too.

Another good to have feature is to control the sampling rate via global config, so we can adjust quickly in similar cases. Oh I should merge the splitting config PR quickly.

**Comment by oxtoacart** [comment]
Wow, 467k events from one client!  I bet that used up a lot of their bandwidth!  We have logic to suppress duplicate messages, but these messages all contain slightly different data so that's not working.

I think we should deduplicate messages on the client-side and report aggregated counts.  We actually already do this with borda, but I suspect the deduplication isn't working well because of the verbose messages.
