### ISSUE TITLE
Why Lantern Get Charged

### ISSUE THREAD

**Issue by liuyonghao156** [getlantern/lantern#5129]
I think it questionable to get charged since Lantern is an open-source software and relies mostly on volunteers who run its client in unblocked areas.

**Comment by myleshorton** [comment]
Thanks for your thoughts @liuyonghao156. I respectfully disagree for a couple of reasons:

1) Lantern is only open source because we choose to make it open source. We shouldn't somehow be penalized for being more generous with our source license. There are also extremely few outside contributions to Lantern.
2) While the original Lantern focused on volunteers running it outside censored regions, more recent versions no longer support that. 

There are multiple reasons for the second, but the biggest one is that purely running through peers running around the world creates very high latency in many cases and therefore a poor user experience for users in censored regions. Beyond that, it can be challenging convincing users in uncensored regions to run access points purely out of good will.

That said, we hope to revisit and bring back many of those p2p elements in a modified form that does not depend as much on low latency connections.

**Comment by liuyonghao156** [comment]
I really appreciate your reply with patience and commitment to this outstanding project, which eventually has optimised our experience. Quite a lot.
