### ISSUE TITLE
最新版的Lantern无法使用

### ISSUE THREAD

**Issue by Juddd** [getlantern/lantern#5362]
我只想收费版都做成样，完全没天理啊，又没有官方的退款渠道，我有点怀疑这项目是专门用来骗我们这些穷学生的钱的。。

**Comment by p3rcya** [comment]
请问具体怎么无法使用？ 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供邀请码。请及时提供，否则我们无法调查。

**Comment by Juddd** [comment]
@p3rcya  有点像段誉的六脉神剑一样--时灵时不灵，不过慢的时候居多，快的时候极少，据感受，在手机端表现还可以，电脑端比我的5块钱一个月的vpn差得远

[logs.zip](https://github.com/getlantern/lantern/files/537914/logs.zip)

**Comment by Amos-zq** [comment]
64位win10企业版，Lantern总是不能用。那个圈圈总是在转。已经买了会员，求对策。 @p3rcya

**Comment by peterhelen** [comment]
win7,最新付费专业版时断时续，什么情况
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/vendor/github.com/getlantern/balancer.(*Balancer).Dial (balancer.go:127)
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/vendor/github.com/getlantern/balancer.(*Balancer).Dial-fm (reverseproxy.go:28)
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/vendor/github.com/getlantern/detour.Dialer.func1 (detour.go:146)
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/client.(*Client).proxiedDialer.func1 (client.go:214)
ERROR balancer: balancer.go:127   at net/http.(*Transport).dial (transport.go:829)
ERROR balancer: balancer.go:127   at net/http.(*Transport).dialConn (transport.go:967)
ERROR balancer: balancer.go:127   at net/http.(*Transport).getConn.func4 (transport.go:885)
ERROR balancer: balancer.go:127   at runtime.goexit (asm_386.s:1612)
ERROR balancer: balancer.go:127 Caused by: Unable to dial server (trusted) chained proxy at 104.199.205.69:34509 [obfs4]: dial tcp 104.199.205.69:34509: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/vendor/github.com/getlantern/chained.(*dialer).Dial (dialer.go:46)
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/vendor/github.com/getlantern/chained.(*dialer).Dial-fm (dialer.go:39)
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/client.(*chainedServer).dialer.func2 (chained.go:136)
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/vendor/github.com/getlantern/balancer.(*dialer).dial (dialer.go:125)
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/vendor/github.com/getlantern/balancer.(*Balancer).dialWithTimeout.func1 (balancer.go:145)
ERROR balancer: balancer.go:127   at github.com/getlantern/flashlight/vendor/github.com/getlantern/context.(*context).Go.func1 (context.go:139)
ERROR balancer: balancer.go:127   at runtime.goexit (asm_386.s:1612)
ERROR balancer: balancer.go:127 Caused by: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[lantern.txt](https://github.com/getlantern/lantern/files/549802/lantern.txt)

**Comment by hinext** [comment]
欢迎测试shadowsocks.

www.note.pw

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
