### ISSUE TITLE
Re-enable a version of forcerecheck that is less bandwidth/resource intensive

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5515]
The intent is to recheck the dialer that's failing, but unfortunately the current logic triggers rechecks for all dialers.

**Comment by oxtoacart** [comment]
So the core problem that @joesis observed is that there's some sort of degenerate case that's triggering checks every few seconds. The intent behind the original design was to have an exponential back-off that results in very few checks at steady state, but that rechecks more aggressively if conditions change (i.e. a proxy starts suddenly failing).

The workaround that's now deployed has the unfortunate side effect of not rechecking at steady state, so if the user's best proxy suddenly starts failing (perhaps because it was restarted), it'll get bumped down the list, and it won't have a chance to move back to first place until the next regularly scheduled check (which at steady state is every 1 hour).

**Comment by oxtoacart** [comment]
This is made obsolete by https://github.com/getlantern/lantern/issues/5174
