### ISSUE TITLE
Security Bug on web UI 安全漏洞 关于网页UI

### ISSUE THREAD

**Issue by wooowooo** [getlantern/lantern#5618]
lantern 3.6.3 for linux

lantern web ui listens on 
网页UI的监听地址为
tcp        0      0 :::36133                :::*                    LISTEN
so anyone can access this ui 
造成任何人可访问此控制界面

using parameter 
即使在命令中加入 
-uiaddr 127.0.0.1:36133
changes nothing 
也无效

**Comment by myleshorton** [comment]
36133 is a random port, though, and lantern restricts access by origin.

On Mar 5, 2017 3:40 AM, "wooowooo" <notifications@github.com> wrote:

lantern 3.6.3 for linux

lantern web ui listens on
网页UI的监听地址为
tcp 0 0 :::36133 :::* LISTEN
so anyone can access this ui
造成任何人可访问此控制界面

using parameter
即使在命令中加入
-uiaddr 127.0.0.1:36133
changes nothing
也无效

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/getlantern/lantern/issues/5618>, or mute the thread

**Comment by wooowooo** [comment]
no, it doesn't deny access from other devices in  LAN. I have tried it. I can change lantern settings with my cell phone browser.
